### PR TITLE
Fix Windows Hardcoding

### PR DESCRIPTION
**Pull request by ghost**
Compiles on Linux & co. now

And also consider getting rid of the partial busy loop as a default.
It makes 0 visual difference and just eats up CPU.
I think it has LESS input lag when it's off, but maybe that's just me, and also shows how little difference it makes that i don't even really know.
I know that's not part of this PR, but something to consider!

### CODE REVIEW

**Comment by raysan5** [comment]
@mr-sihc thanks for the review. Note that the busy wait loop could be disabled with a flag is desired.

**Comment by Peter0x44** [comment]
Actually, `#include "SDL.h"` is the official SDL-recommended way to do it.
I think you should review how you build raylib yourself, this change is not a good idea.

**Comment by mr-sihc** [comment]
Its how its installed on Arch and everywhere else

**Comment by Peter0x44** [comment]
That's not true
`pkg-config --cflags sdl2` returns `-I /usr/include/SDL2`

**Comment by mr-sihc** [comment]
then the Makefile does it wrong, which i used, and the cmake file has outdated doesnt even list SDL as an option

**Comment by raysan5** [comment]
@mr-sihc @Peter0x44 Just reverted this cahnge, checked the official SDL examples and they use `#include "SDL.h"`. Following the same pattern as the creators of SDL.

**Comment by Peter0x44** [comment]
@mr-sihc Sorry, you're just wrong.
There's no other way to put it.
SDL2/SDL.h only works by accident, because your compiler automatically searches in /usr/include.
Both pkg-config and sdl2-config indicate that #include "SDL.h" is the intended and endorsed way to include the header.
It has nothing to do with "subprojects" or not, in fact it actually accommodates "subprojects" better to do it this way.

**Comment by Peter0x44** [comment]
>  i like this, are you going to include this failsafe in the makefile?
I'm not sure. I do think it's a good idea, but I don't know if Ray would approve. It could work on Windows too, but it needs a posix-sh type shell, not cmd.exe.
A better idea might be to put it behind an:
```make
ifeq ($(PLATFORM_OS), $(filter $(PLATFORM_OS), LINUX BSD OSX))
# ...
endif
```
I'm unlikely to have enough time to formalize a PR for this, but I'm happy to review any such PR if you choose to submit it.

**Comment by mr-sihc** [comment]
> > i like this, are you going to include this failsafe in the makefile?
> 
> I'm not sure. I do think it's a good idea, but I don't know if Ray would approve. It could work on Windows too, but it needs a posix-sh type shell, not cmd.exe. A better idea might be to put it behind an:
> 
> ```makefile
> ifeq ($(PLATFORM_OS), $(filter $(PLATFORM_OS), LINUX BSD OSX))
> # ...
> endif
> ```
> 
> I'm unlikely to have enough time to formalize a PR for this, but I'm happy to review any such PR if you choose to submit it.

Hmm, i'll see tomorrow if i could make it work.
But no promises i dont know much about makefiles xD!

If Ray even approves... Would this be a nice thing in the makefile?

**Pull request merged**
