### PR TITLE
Don't create an ortho matrix when the viewport is 0 in any axis.

### PR DESCRIPTION
**Pull request by JeffM2501**
Not all compilers divide by 0 and return inf, some segfault.
This PR skips the ortho matrix in the resize callback when any axis is 0, to prevent any divide by 0 errors that may come up.
The matrix is not used by anything when minimized, so it just needs to not be called.
The correct matrix will be created when the window is restored.

### CODE REVIEW

**Comment by raysan5** [comment]
@JeffM2501 Hey! I think `core_basic_window` shouldn't be in this PR...

**Comment by JeffM2501** [comment]
> @JeffM2501 Hey! I think `core_basic_window` shouldn't be in this PR...

That is correct, that is my test file :( I'll see if I can figure out how to remove that

**Comment by JeffM2501** [comment]
Ok, it should be good now, the example file is not part of the changed files in the PR. I'm very sorry about that.

**Comment by raysan5** [comment]
@JeffM2501 Thanks for the improvement! :)

**Pull request merged**
