### PR TITLE
Fix deprecation error on android api higher than 23

### LINKED ISSUE #2772: [build] __ANDROID_API__ version is hardcoded to value incompatible with most of the recent android targets
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

raylib is seemed to be hardcoding android api version to 21 which is pretty old and incompatible with build targets above 23 ( which is most of the devices out there ).
The value is specified in LibraryConfigurations.cmake.

### Environment

Build for android on windows.

### Issue Screenshot

C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/external/tinyobj_loader_c.h:751:13: error: '__sF' is unavailable: obsoleted in Android 23
    fprintf(stderr, "TINYOBJ: Error reading file '%s': %s (%d)\n", filename, strerror(errno), errno);
            ^
C:/Users/serge/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdio.h:76:18: note: expanded from macro 'stderr'
#define stderr (&__sF[2])
                 ^
C:/Users/serge/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/stdio.h:72:13: note: '__sF' has been explicitly marked unavailable here
extern FILE __sF[] __REMOVED_IN(23);
            ^
In file included from C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/rmodels.c:69:
C:/Users/serge/source/myproject/build_android/arm64-v8a/_deps/raylib-src/src/external/tinyobj_loader_c.h:1326:15: error: '__sF' is unavailable: obsoleted in Android 23
      fprintf(stderr, "TINYOBJ: Failed to parse material file '%s': %d\n", filename, ret);

### PR DESCRIPTION
**Pull request by anggape**
this changes fixes #2772

### CODE REVIEW

**Comment by raysan5** [comment]
@anggape This commit adds a binary .jar file to the repo, I think that file shouldn't be added.

**Comment by anggape** [comment]
according to https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html this file needed to be included

> The scripts generated by this task are intended to be committed to your version control system. This task also generates a small gradle-wrapper.jar bootstrap JAR file and properties file which should also be committed to your VCS. The scripts delegates to this JAR.

**Comment by orcmid** [comment]
@anggape I was looking at this concerning Wrapper.

> Generates scripts (for *nix and windows) which allow you to build your project with Gradle, without having to install Gradle.

That seems to end up with Gradle being cached anyhow.  For something as heavy-duty as Android Studio, why not just have Gradle as a prerequisite?  

Maybe a better question: Is this standard practice when distributing project solutions/templates for Android Studio?

**Comment by anggape** [comment]
removed

**Comment by raysan5** [comment]
@anggape thanks, I also prefer to keep the PRs self-contained instead of solving multiple issues

**Pull request merged**
