### PR TITLE
Add rewind for the XM music format

### LINKED ISSUE #843: [raudio] .XM music files doesn't restart when stop->play
When a music stops It should restart on play. But it is not working for .xm module files. It is just pausing the music.
Looks like it is not available [in source](https://github.com/raysan5/raylib/blob/c1594fa445d038e40bae22eb69dfa04cc406aca4/src/raudio.c#L1338) or am I missing something?

### PR DESCRIPTION
**Pull request by wbrbr**
Disclaimer: I don't know the XM format (at all) and I don't know jar_xm.h at all
But hey, this seems to work on all the files I have tested on.

Fixes #843

### CODE REVIEW

**Comment by raysan5** [comment]
Maybe that function should be inside jar_xm...

**Comment by selimanac** [comment]
Strange but unfortunately this doesn't work for me :(  I test it with 2 xm files.  When I `StopMusicStream`->`PlayMusicStream` with `jar_xm_reset` it continue to play from where it left-off

**Comment by raysan5** [comment]
@wbrbr I think you removed the function call from `raudio.c` :P

**Comment by wbrbr** [comment]
@raysan5 I think it looks fine, did I miss something ?

@selimanac can you try [this minimal example](https://gist.github.com/wbrbr/f135f59d988099c045ada07a4fa4d6f8) and tell me if it works ? It should restart when you hit the spacebar. (don't forget to link it with the patched raylib)

**Comment by raysan5** [comment]
@wbrbr it's perfect now! Maybe it was an issue with the browser...

**Comment by selimanac** [comment]
> @selimanac can you try [this minimal example](https://gist.github.com/wbrbr/f135f59d988099c045ada07a4fa4d6f8) and tell me if it works ? It should restart when you hit the spacebar. (don't forget to link it with the patched raylib)

Thank you. It worked with 'mini1111.xm' but not with this random ones : 
https://modarchive.org/index.php?request=view_by_moduleid&query=59963 
https://modarchive.org/index.php?request=view_by_moduleid&query=43516

**Comment by selimanac** [comment]
> @wbrbr it's perfect now! Maybe it was an issue with the browser...

I'm not using browser, compiling and testing it with xcode

**Comment by selimanac** [comment]
> @selimanac can you try [this minimal example](https://gist.github.com/wbrbr/f135f59d988099c045ada07a4fa4d6f8) and tell me if it works ? It should restart when you hit the spacebar. (don't forget to link it with the patched raylib)

Ah. When I `change ctx->current_table_index = 1;` to `ctx->current_table_index = 0;` it works :)

**Comment by wbrbr** [comment]
@selimanac sorry I didn't respond earlier. The problem is that `current_table_index = 0` doesn't work with some files (like mini1111.xm: it plays some kind of drum break before restarting). If I get the time I will try to investigate this, but I don't know this data format at all unfortunately

**Comment by wbrbr** [comment]
@selimanac  I may have found a fix ! Can you confirm that it works if you replace `ctx->current_table_index = 0` with `ctx->current_table_index = ctx->module.restart_position` ?

**Comment by selimanac** [comment]
@wbrbr I quickly tested with 5 different xm files including mini111. All works fine for me.

**Comment by wbrbr** [comment]
Okay I'll make another PR soon

**Pull request merged**
