### PR TITLE
Added DrawTextStyle() and DrawTextStyleEx() for Drawing Styled Text with Markdown

### PR DESCRIPTION
**Pull request by OkiStuff**
Added DrawTextStyle() and DrawTextStyleEx() for Drawing Styled Text with Markdown

This is modified code of https://github.com/NightenDushi/Raylib_DrawTextStyle. I feel like it would be nice to have this built-in instead of as a header. But I 100% understand if you don't want to add it in. It would be a little weird for a framework to have a feature like this. Just feel like because one of the goals of raylib is to be easy-to-use library to enjoy making games this would make it easier to do cool stuff with text.

### CODE REVIEW

**Comment by OkiStuff** [comment]
after getting some feedback from the community
it would be better to take it down

**Comment by raysan5** [comment]
@OkiStuff Maybe it's a bit specific feature to be added to raylib but undoubtedly it should go into a code example!

**Comment by vaartis** [comment]
At least _some_ support for styling not provided by fonts would be nice, like underline and strikethrough. It's already implemented in the PR, maybe something more scaled down from this could be implemented. Some libraries implement routines to create bold and italic fonts themselves, too (sdl_ttf and SFML at least).

**Comment by raysan5** [comment]
@vaartis All those extras can actually be implemented at user level, no need to be provided by raylib. In any case, an example with those features implemented would be nice.

**Pull request closed without merging**
