### PR TITLE
make const

### PR DESCRIPTION
**Pull request by planetis-m**

### CODE REVIEW

**Comment by planetis-m** [comment]
Others that could also be const is UpdateMeshBuffer, rlUpdateVertexBuffer

**Comment by raysan5** [comment]
There are several functions that input parameters can be `const` but I'm only using it for `const char *`. I prefer to keep it that way.

**Comment by raysan5** [comment]
@planetis-m I reviewed this issue more carefully and I'm adding some additional consts.

**Comment by planetis-m** [comment]
So you annotated all const pointers? Thats awesome, hopefully it would help bindings devs figure out if it's an out parameter without looking at the code.

**Comment by raysan5** [comment]
@planetis-m Not all but most of them.

**Pull request merged**
