### PR TITLE
Code refractoring of music module to be more user-friendly (issue #144)

### PR DESCRIPTION
**Pull request by Bil152**
It's a basic rework of the Music module to be more user-friendly like in the [issue #144 ](https://github.com/raysan5/raylib/issues/144)

### CODE REVIEW

**Comment by Bil152** [comment]
I forgot ... If you want [to test](https://gist.github.com/Bil152/14a613b9c270093684237f616c365640)

**Comment by raysan5** [comment]
Hi @Bil152, many thanks for the update!

Just a little issue: I think you implement those changes without sync to latest develop branch because some of my latest changes in audio module are overwritten. Please, could you try syncing to latest develop and update the pull request?

Probably I will review some naming and functions but this update is a good start! Thanks!

**Comment by Bil152** [comment]
Hello !

First of all thanks :D ! 
But I don't understand ... I used audio.c from the latest commit, well, it's weird !
So I need to take audio.c from a little older commit and add here my changes ?

**Comment by raysan5** [comment]
Hi @Bil152,

If you check the last updates in the line: https://github.com/raysan5/raylib/network

On commit "Updated log output info" (https://github.com/raysan5/raylib/commit/6d68c789891b35f06724bea9436db91f3bd17fcf) I updated `audio.c` and those changes are not in your branch. 

Don't worry, not that big issue, it usually happens. I can just accept the pull and reimplement the changes (not that much) or implement them yourself and add a new commit to the pull-request.

I'll do first option because I also have some additions to `raylib.h`.

Just a note for the future, before doing a pull request we should discuss it on the related issue because I also keep working on that branch an those files and we should try to avoid overlapping.

**Comment by Bil152** [comment]
OK ! Sorry for this little issue (working in open source with other people is pretty new for me)... I will try to be more careful !
Thanks :D !

**Comment by raysan5** [comment]
No worries! Thank you very much for your contribution! :D

**Pull request merged**
