### PR TITLE
Allow building raylib directly into zig binaries

### PR DESCRIPTION
**Pull request by dantecatalfamo**
Instead of returning a compile step for a static library from `addRaylib`, we make it add the required C source files and their compilation flags onto an existing compile step.

This lets us add raylib directly to any zig project by just calling `addRaylib(b, exe)` on our zig compilations within other build files.

I've also defined the `-DPLATFORM_DESKTOP` flag only for the C compilation units directly related to raylib, so if we're compiling into another zig project that includes other C source files, they don't see any raylib-related flags.

For example, I'm working on a project that uses raylib to create a graph. Now all I have to do to compile my project with raylib is this.

```zig
const raylib = @import("deps/raylib/src/build.zig");
/// [...]
    const exe = b.addExecutable(.{
        .name = "zig-visual",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });
raylib.addRaylib(b, exe, .{ .raygui = true });
/// [...]
```

### CODE REVIEW

**Comment by raysan5** [comment]
@dantecatalfamo This seems to be a big change on the raylib compilation. Does it fit all Zig users needs?

**Comment by dantecatalfamo** [comment]
@raysan5 It should make it much easier to integrate raylib into any zig project. It works well for me but I would be happy to see other zig developers comment on this

**Comment by dantecatalfamo** [comment]
I should also add the include path of the raylib src directory to the executable passed in. I'm not home right now but I'll add that later

**Comment by Not-Nik** [comment]
I don't really see the point in this. Linking with raylib before was one line more than it is with this PR, so this doesn't really change much in that area and building a standalone version of raylib would be made unnecessarily complicated. Also setting options for raylib seperately is no longer possible, so you can't mix an optimized raylib build with a debuggable executable. I'd rather have more fine control over the raylib part of my build than have one less line in my build script.

**Comment by DaJobat** [comment]
I'm with @Not-Nik, this actually is less useful than the current way of building raylib. It'd be fine as an option, but as a replacement it's a bit of a downgrade.

**Comment by dantecatalfamo** [comment]
I didn't realize you could link compile steps together using `linkLibrary`, sorry for the confusion!

**Pull request closed without merging**
