### PR TITLE
fix build paths

### PR DESCRIPTION
**Pull request by hardliner66**
I figured out what the problem for #3834 was and found a solution to fix it as well.

The first problem was, that `srcdir` is an absolut path, but using `.{.path = ...}` is supposed to be relative only. So I instead changed it to use `.cwd_relative` which is badly named, but the appropriate field to use for absolute paths.

The next problem was, that the files added via `addCSourceFilesVersioned` needed to be relativ to the module (raylib itself) so I figured out a way to get the relative path and added that too.

~~Theres still a minor problem with getting the relative path, but that shouldn't take that long to fix.~~

### CODE REVIEW

**Comment by hardliner66** [comment]
Fixed the final problem as well. Raylib now compiles on it's own and inside my project without problesm.

**Comment by raysan5** [comment]
@hardliner66 Some experienced zig developer should review this change. I feel it adds an extra level of complexity, not sure if really required.

**Comment by raysan5** [comment]
@hardliner66 Thanks for the detailed explanation. I'm merging it.

**Comment by hardliner66** [comment]
No problem. I analyzed the bug and fixed it, so I should also explain it. But yesterday it was already 2:30am when I created the MR, so my explanation skills weren't the best probably :sweat_smile:

**Pull request merged**
