### PR TITLE
[core] Create function to retrieve frame busy time (non-sleeping time)

### PR DESCRIPTION
**Pull request by bmbkr**

### CODE REVIEW

**Comment by bmbkr** [comment]
I still need to update documentation throughout the repo to include this new function.

That being said, I'm eagerly awaiting your thoughts on this new functionality @raysan5

**Comment by raysan5** [comment]
@bmbkr I prefer to avoid exposing this internal state, most users probably do not need it and advance users can implement it for their needs or just enable `SUPPORT_CUSTOM_FRAME_CONTROL` on `config.h` to have full control over the frame.

Exposing this state would imply exposing other internal states that I think most users do not need at the moment.

**Comment by bmbkr** [comment]
@raysan5 Understood. Perhaps this can be exposed at some point in the future as part of a metrics interface, simply as a ratio of busy to sleep time. Would be particularly useful for performance measurement, although as you said you can just recompile with custom frame control.

**Comment by raysan5** [comment]
@bmbkr there was a new feature in that line in the past (https://github.com/raysan5/raylib/issues/1295) but it required to many changes and coupling and it was discarded...

**Pull request closed without merging**
