### PR TITLE
[example] Input virtual controls example

### PR DESCRIPTION
**Pull request by oblerion**
lighter, simpler #4333,
works with mouse and touch inputs.

depends : math.h for fabsf() 

- [x] 1. rename example .c with [module][example] in 3 worlds
- [x] 2. author short description 
- [ ] 2. example info should list the module
- [x] 3. organized section [Initialization]- [Update] - [Draw] - [De-Initialization]
- [x] 4. rename variables in lowerCase    
- [x] 5. commented example  
- [x] 6. less 300 lines
- [ ] 6. avoid external dependencies
- [x] 6. no function outside main()
- [x] 7. external resources in resources folder
- [x] 8. keep it simple
- [ ]  8. creative touch

### CODE REVIEW

**Comment by raysan5** [comment]
@oblerion Please, could you review the requirement to add a new raylib example: https://github.com/raysan5/raylib/blob/master/examples/examples_template.c

**Comment by oblerion** [comment]
- [x] 1. rename example .c with [module][example] in 3 worlds
- [x] 2. author short description 
- [ ] 2. example info should list the module
- [x] 3. organized section
- [x] 4. rename variables in camelCase    
- [x] 5. commented example  
- [x] 6. less 300 lines
- [ ] 6. avoid external dependencies
- [x] 6. no function outside main()
- [x] 7. external resources in resources folder
- [x] 8. keep it simple
- [ ]  8. creative touch

**Comment by raysan5** [comment]
@oblerion Just to clarify the requirements:

 - [x] raylib/examples/<category>/<category>_example_name.c
 - [x] raylib/examples/<category>/<category>_example_name.png
 - [x] raylib/examples/<category>/resources/*.*
 - [ ] raylib/examples/Makefile
 - [ ] raylib/examples/Makefile.Web
 - [ ] raylib/examples/README.md
 - [ ] raylib/projects/VS2022/examples/<category>_example_name.vcxproj
 - [ ] raylib/projects/VS2022/raylib.sln

Also note that current example is not following required [coding conventions](https://github.com/raysan5/raylib/blob/master/CONVENTIONS.md).

About the example name, I think it could be `core_input_virtual_controls`, because it could also add visual buttons or visual thumb-stick in the future.

**Comment by raysan5** [comment]
@oblerion Are you going to complete the following requirements for example addition?

 - [ ] raylib/examples/Makefile
 - [ ] raylib/examples/Makefile.Web
 - [ ] raylib/examples/README.md
 - [ ] raylib/projects/VS2022/examples/<category>_example_name.vcxproj
 - [ ] raylib/projects/VS2022/raylib.sln

**Comment by oblerion** [comment]
- [x] raylib/examples/Makefile
- [x] raylib/examples/Makefile.Web
- [x] raylib/examples/README.md
- [ ] raylib/projects/VS2022/examples/_example_name.vcxproj
- [ ] raylib/projects/VS2022/raylib.sln

**Pull request merged**
