### PR TITLE
Update zig build system to zig version 0.11.0

### LINKED ISSUE #3386: [build] Cannot build examples with zig 0.11.0, build.zig needs to be updated
### Issue description

I followed instructions in `examples` folder and built with command `zig build core`, but so many errors occurred.

### Environment

Windows 10 LTSC x64, raylib `4.5.0`, zig `0.11.0`

image

### Issue Screenshot

I tried some fixing and was stuck here...

image
image
image
image

### PR DESCRIPTION
**Pull request by purple4pur**
Discard `build.zig` and use `src/build.zig` only, bc by default these two output in different directories.

build command: cd to `src` then `zig build`.

Close #3386

### CODE REVIEW

**Comment by raysan5** [comment]
@purple4pur thanks for the review!

**Comment by Not-Nik** [comment]
Unfortunately, removing the top-level `build.zig` wrecks compatibility with Zig's builtin package manager

**Comment by star-tek-mb** [comment]
Yeah. Revert PR please. Latest raylib is up to date with latest zig. Feel free to find commit version which suites your zig version.

**Comment by raysan5** [comment]
@Not-Nik @star-tek-mb should this PR be reverted?

**Comment by purple4pur** [comment]
@Not-Nik Ohh thanks for this infomation! 

@star-tek-mb Tested with master branch raylib and zig 0.11.0, `build.zig` and `src/build.zig` are ready to go, but `examples/build.zig` fails (same as #3386), which is this PR mainly about.

Let me do more checks on both latest master branches and zig's package manager

**Comment by star-tek-mb** [comment]
Ok. Thanks. I was mainly arguing with top level build.zig. I need it in my projects.

Sorry for maybe my rude messages. Let me know if you need any help with examples. I will check on zig master later.

**Comment by purple4pur** [comment]
@star-tek-mb nvm, your suggestion helps a lot! Also I tested with latest zig `0.12.0-dev.817+54e7f58fc`, updating `examples/build.zig` is still needed

@Not-Nik @star-tek-mb I checked zig's package manager and tried the demo https://github.com/ziglang/zig/issues/14278, top-level `build.zig` seems necessary. At the point before this PR, confusing problems are:

1. Running `zig build` at top-level gets `zig-out` at top-level (which is expected). Running `zig build` in `src` gets errors complaining at https://github.com/raysan5/raylib/blob/cfffa74f96c06231f6fa327e9cc52863b18d52b2/src/build.zig#L195-L197 `error: unable to update file from 'raylib\src\src\raylib.h' to 'raylib\src\zig-out\include\raylib.h': FileNotFound`
2. If fix above lines then top-level complains.
3. `examples/build.zig` uses `src/zig-out` not `zig-out` https://github.com/raysan5/raylib/blob/cfffa74f96c06231f6fa327e9cc52863b18d52b2/examples/build.zig#L30-L33

So my ideas:

* **Option 1:** fix `src/build.zig` to **1.** have no conflict with top-level `build.zig` and **2.** always output `zig-out` to top-level
* **Option 2:** keep only one `build.zig` at top-level, discard `src/build.zig`
* **Option 3:** keep them there, but add a note to `src/build.zig`, which reminds users not to build in `src`

I've tried Option 1 before this PR, but still don't solve :(
Any suggestions?

**Comment by Not-Nik** [comment]
> Also I tested with latest zig 0.12.0-dev.817+54e7f58fc, updating examples/build.zig is still needed

I strongly oppose updating Zig to a pre-release version.

As for the `build.zig` positions, I don't think any changes are necessary from the version before this PR.

**Comment by purple4pur** [comment]
OK. I then open a PR to revert changes on `build.zig` and `src/build.zig` and just focus on `examples/build.zig` with zig 0.11.0.

Much appreciated @Not-Nik !

**Pull request merged**
