### PR TITLE
Add Vector2Dir function to get the direction vector of two given points

### PR DESCRIPTION
**Pull request by Elkantor**
I always add this function anyway on my raylib projects, so I think that could be usefull to get this function directly in raymath.
But it's really not mandatory.
Note: the function name is quite "quick and dirty", but hey, it is probably enough?

### CODE REVIEW

**Comment by Peter0x44** [comment]
Isn't this just Vector2Subtract with the arguments flipped? What's the need for this?

**Comment by Elkantor** [comment]
> Isn't this just Vector2Subtract with the arguments flipped? What's the need for this?

Yes, totally! Indeed, but actually it's just the name which matters. Anyway, I didn't even took attention to Vector2Substract! Gosh I'm tired haha

**Comment by idircarlos** [comment]
I understand the intention of @Elkantor. Calculating the direction vector of a line (or a plane) is a common operation when working with vectors. Here is my opinion on this. In case we are adding the function, I would: 
- Rename it to `Vector2Direction`, which is a more self-explanatory.
- `Vector2 result = Vector2Subtract(v2, v1);` instead of `Vector2 result = { p2.x - p1.x, p2.y - p1.y };`
- Add the same function for a plane (defined by 3 points)

But this is just my opinion :) I hope it helps.

**Comment by raysan5** [comment]
@Peter0x44 thanks for looking into this, I was aware of some similar function already available.

@Elkantor @idircarlos A `Vector2Direction()` could be useful but probably as a normalized vector, afaik a direction is more useful normalized, right? Not sure if there is any similar alternative.

**Pull request closed without merging**
