### PR TITLE
add multi channel audio to raudio

### PR DESCRIPTION
**Pull request by chriscamacho**
as it says on the tin, please see the example for usage...

### CODE REVIEW

**Comment by raysan5** [comment]
Thanks for the improvement @chriscamacho! This month I'm very busy preparing a presentation for next week but I'll review it as soon as possible! :)

**Comment by raysan5** [comment]
@chriscamacho thanks for the addition! I'll review it carefully...

For next time, please check raylib [coding conventions](https://github.com/raysan5/raylib/wiki/raylib-coding-conventions)

**Comment by chriscamacho** [comment]
On Sat, 29 Jun 2019 01:49:51 -0700
Ray <notifications@github.com> wrote:

> @chriscamacho thanks for the addition! I'll review it carefully...
> 
> For next time, please check raylib [coding
> conventions](https://github.com/raysan5/raylib/wiki/raylib-coding-conventions)
> 

I thought I had, what did I miss ??

---
bedroomcoders.co.uk - coding adventures of a geek...

**Comment by raysan5** [comment]
Just reviewing it!

**Pull request merged**
