### PR TITLE
Add virtual Dpad example (Use full for Android)

### PR DESCRIPTION
**Pull request by GreenSnakeLinux**
Add virtual Dpad example (Use full for Android)
Use of new ColorLerp function

### CODE REVIEW

**Comment by GreenSnakeLinux** [comment]
Maybe some adjustments should be done
This example can also be part of the CORE source to provide a DPad for Android version, as you whish

**Comment by oblerion** [comment]
DPads are also very useful for online touch games,
The code can be simplified, but can be hacked for other inputs.

Interesting, all that's missing is the abxy Dpad.

**Comment by raysan5** [comment]
@GreenSnakeLinux The example does not follow required conventions and format to be added to raylib. If you want to add an example, please follow required process as commented in the template: https://github.com/raysan5/raylib/blob/master/examples/examples_template.c

**Comment by raysan5** [comment]
Please, resend the PR once the new-example guidelines are met. Thanks.

**Pull request closed without merging**
