### PR TITLE
Add Keyboard Input

### PR DESCRIPTION
**Pull request by SamNChiet**
This adds keyboard input polling for UWP.

### CODE REVIEW

**Comment by SamNChiet** [comment]
It's noteworthy that there's a known 'bug' where UWP reports repeated key presses after holding a key down for too long.
I'm not sure how to fix it, it'll take some looking into.

**Comment by raysan5** [comment]
Thanks for the update @SamNChiet! Please could you remove all the binaries and intermediate files from the PR?

**Comment by OMERCY** [comment]
Have you try working in the binaries?

**Comment by SamNChiet** [comment]
Oh, that was silly of me. I'll fix that once I get home.

(I'm responding to this via email, we'll see if this even goes through!)

**Comment by SamNChiet** [comment]
Alright, we'll see if that worked.
I noticed the automatic build system on AppVeyor is having trouble determining which project/solution to build...

**Comment by raysan5** [comment]
Hi @SamNChiet! Thanks for the review! Merging...

**Pull request merged**
