### PR TITLE
fixed leaks, also see pbr example review required

### PR DESCRIPTION
**Pull request by chriscamacho**
leak in models, also leak todo with multichannel audio fixed
please see pbr example, encountered an issue I'm not sure the best way to fix....

### CODE REVIEW

**Comment by raysan5** [comment]
ouch... @chriscamacho PR should be accumulated to previous...

**Comment by raysan5** [comment]
@chriscamacho Would you mind synching to current master and closing-resending this PR?

**Comment by chriscamacho** [comment]
I literally forked it minutes before making the PR ?

**Comment by raysan5** [comment]
@chriscamacho yeah, but I merged and now current master conflicts with your previous PR, that was not merged yet... Usually commits from the same user are accumulated into previous open PRs, I don't know why a new PR was generated on this case...

In any case, no worries, I can merge changes manually.

**Comment by chriscamacho** [comment]
Better yet dump my previous PR, just take the last

there are issues with the pbr example but I nearly have it once I do
I'll do a PR for that separately...




On Thu, 19 Sep 2019 07:23:28 -0700
Ray <notifications@github.com> wrote:

> @chriscamacho yeah, but I merged and now current master conflicts
> with your previous PR, that was not merged yet... Usually commits
> from the same user are accumulated into previous open PRs, I don't
> know why a new PR was generated on this case...
> 
> In any case, no worries, I can merge changes manually.
> 



---
bedroomcoders.co.uk - coding adventures of a geek...

**Pull request closed without merging**
