### PR TITLE
 Deal with failed LoadMusicStream

### PR DESCRIPTION
**Pull request by jubalh**
It would be good to have a way to continue execution even when loading a stream didn't work.
 Free music and set it to NULL in case something went wrong, so that users can check for it.

### CODE REVIEW

**Comment by jubalh** [comment]
@a3f changed

**Comment by raysan5** [comment]
Merging but I need to review this (maybe change it), I don't like at all that `format` parameter.

**Comment by raysan5** [comment]
@jubalh just reviewed changes in commit https://github.com/raysan5/raylib/commit/dc3327fba8df91b252f911cca8b26621622d3488, finally I removed the additional function and moved code inside `LoadMusicStream()`. I prefer to avoid additional functions for something that specific.

**Comment by raysan5** [comment]
Yeah, it's true but message is generic enough to let the user understand that something is wrong with the file he/she tries to load. I'll assume that minimal lack of information.

**Pull request merged**
