### PR TITLE
SNES-like GAMEPAD Support added for Android, Makefile has optional support for 32bit

### PR DESCRIPTION
**Pull request by SethArchambault**
#567 

This is my first ever significant pull request! I love that that raylib is so easy to comprehend.

Note that in getting the gamepad feature to work, I had to abort before the gestures system could be handled. I tried some methods for ignoring gestures only when gamepad input was detected, however the system seems really glitchy (pointerCount seems to go all over the place), and I had to give up. Perhaps someone who is doing gesture stuff can step in here and try to re-enable it. 

The gamepad feature is really simple, all I had to do was capture the keycode when motion was detected, no axis needed for this one. 

I've tested this with Android, wasn't able to test elsewhere right now. Won't be offended if this is rejected for that reason! Was a great experience solving this myself, I'm so glad I'm using a code base that I can actually reason about!

Seth

### CODE REVIEW

**Comment by SethArchambault** [comment]
Oh, and I recognize the 32bit support may be unwanted.. Sorry!

**Comment by SethArchambault** [comment]
Thinking on this more, instead of calling these enums like this:
GAMEPAD_SNES_DPAD_DOWN   
They should have the word Android in them like:
GAMEPAD_ANDROID_DPAD_DOWN
Since this is linked to the platform, rather than the specific controller..

**Comment by raysan5** [comment]
Great work @SethArchambault! 

If you want to review some part you can add commits to this PR.

I'll review it more carefully tomorrow but it looks very good to me! :)

**Comment by raysan5** [comment]
ok, I'm merging it and I'll review it.

**Pull request merged**
