### PR TITLE
Create models_third_person

### PR DESCRIPTION
**Pull request by PompPenguin**
Let me know if any code clean up is needed.

### CODE REVIEW

**Comment by PompPenguin** [comment]
Line 138: Typo, It should say // Unload texture

**Comment by raysan5** [comment]
Hi @PompPenguin! What happened with this PS? Why you closed it? I didn't have time to review it yet...

**Comment by PompPenguin** [comment]
There were some issues when it was doing the pre checks for the code. Looks like it failed on Android compiling. I can reopen it if you would like.

**Comment by raysan5** [comment]
Ok, I see! In any case, you can leave the PR open and just accumulate commits to it, instead of closing it and opening a new one... Just let me know when you think it's ready for merging! :)

**Comment by PompPenguin** [comment]
Got ya! I'm still pretty new to using Github. It should ready besides the issues with Android. I posted a copy of the code on Discord if you want to check it out!

**Pull request closed without merging**
