### PR TITLE
Update Makefile of 'src/' folder

### PR DESCRIPTION
**Pull request by LelixSuper**
Hi, I'm updating the makefile of 'src/' folder with lots of improvements.
I've opened a pull request to notify @raysan5 about my work, because **it is not finished**, and, obviously, to discuss about what I'm doing.

My objectives:
- [x] adjust the name of targets;
- [x] add install / unistall targets for GNU/Linux platform;
- [x] add possibility to compile web and shared versions of raylib;
- [x] review clean target;
- [x] review the compiling of modules (maybe I will use a wildcard).

### CODE REVIEW

**Comment by raysan5** [comment]
Wow! It's been close, I was just going to update Makefile also! I've been doing some changes too... :P

I'm revieweing output folder for all platforms to point to release folder (`src/.../release`).

I will wait for your changes to integrate mines.

**Comment by LelixSuper** [comment]
@raysan5 ok, I think I will complete these points by two-three days.

**Comment by LelixSuper** [comment]
I have a question @raysan5: the file `external/stb_vorbis.c` must be compiled?

**Comment by raysan5** [comment]
Hi @LelixSuper, yes `external/stb_vorbis.c` must be compiled to support OGG audio loading.

**Comment by raysan5** [comment]
I've seen you have group the compilation of all modules into one line, it's ok... I just did the other way to use the file for teaching pourposes (and keep it simple)... but I think that at this point the file has changed so much that it doesn't matter...

**Comment by LelixSuper** [comment]
I have discovered that I can't compile all modules into one line, because each module requires special prerequisite. I'm fixing this problem.

**Comment by raysan5** [comment]
Just a note, some modules (`camera.c`, `gestures.c`) do not require the header because functions are already declared in `raylib.h`. Headers (`camera.h`, `gestures.h`) are provided if someone wants to use the module independently of raylib (hooking their own input functions).

The same way, many modules depend on header-only modules (`stb_image.h`, `sbt_truetype.h`...). And some header-only modules are also provided with raylib (some of them not compiled within raylib - `physac.h`, `raygui.h`, `easings.h`) to be used independently of the library (if someone needs them).

That's done that way to keep raylib as much clean and self-contained as possible and modular. The only problem is that some of those modules are never noticed by users...

**Comment by raysan5** [comment]
You can read a bit more on raylib structure here: https://github.com/raysan5/raylib/wiki/raylib-arquitecture

**Comment by LelixSuper** [comment]
@raysan5 now the makefile can compile raylib (not standalone modules) to shared (Linux), web and static version.
To compile standalone modules, makefile needs other works, meanwhile I'm about to write the docs to compile the library.

**Comment by raysan5** [comment]
Great addition @LelixSuper! Don't worry about standalone modules, they are intended to be dropped into user project (and custom pipeline). They are not intended to be compiled with raylib as standalone.

Is it possible to add DLL compilation with MinGW? It would be great...

Anyway, thank you very much for your effort!

**Comment by LelixSuper** [comment]
@raysan5 I don't know how DLL works on Windows, so I will inform.

**Comment by raysan5** [comment]
Don't worry @LelixSuper, I can take a look later... I'd need to close this pull-request to add it to raylib 1.5, I'm about to publish this new version! Have you finished on your side?

**Comment by LelixSuper** [comment]
@raysan5 I will finish by today.

**Comment by raysan5** [comment]
That's great! Thank you very much @LelixSuper!

**Comment by raysan5** [comment]
By the way, could you upload `libraylib.a` to [release folder](https://github.com/raysan5/raylib/tree/develop/release/linux), it would be great to make it available to the users... :)

**Comment by LelixSuper** [comment]
@raysan5 I have finished. Maybe it needs improvements, I will review him in the future.

**Comment by raysan5** [comment]
Amazing @LelixSuper! Thank you very much for your update! :D

**Pull request merged**
