### PR TITLE
GetDeltaMouse() added.

### PR DESCRIPTION
**Pull request by adricoin2010**
Hello, this is my first Pull Request, sorry if it is not well created.

This pull request adds `GetDeltaMouse()`. It is a simple function that returns the movement of the mouse for each frame.

It can be useful for interfaces, cameras, etc. I need it for a project, and seeing that it was not in raylib I decided to add it.

Greetings.

### CODE REVIEW

**Comment by raysan5** [comment]
@adricoin2010 I'm afraid I'm not adding this functionality, it can be implemented in user side instead of adding two additional global variables to CORE structure.

**Comment by raysan5** [comment]
@adricoin2010 Just registering mouse previous position for a special need, so `GetDeltaMouse()` can be added if you wish.

**Comment by adricoin2010** [comment]
I would love if you could add it. Do I submit a pull request?

**Comment by raysan5** [comment]
@adricoin2010 feel free to send a PR, `GetMouseDelta()` can calculate it directly, no need for extra variables.

**Pull request closed without merging**
