### PR TITLE
Update Audio Libraries

### PR DESCRIPTION
**Pull request by mackron**
This updates the following libraries to their latest versions:
- mini_al v0.8
- dr_flac v0.9.7
- dr_wav v0.8.1
- dr_mp3 v0.2.5

Here's what you'll get:
- Support for Core Audio on Apple platforms which should give better latency than the OpenAL backend.
- PulseAudio and JACK backends for Linux. PulseAudio is the new default backend for Linux.
- A simplified build system for Linux. Development packages for ALSA (and those of any other backend on Linux) are no longer required.
- Fixes to the build for WASAPI and DirectSound backends when compiling with MinGW.
- General bug fixes and optimizations including some early work on SSE2 and NEON SIMD optimizations.

### CODE REVIEW

**Comment by raysan5** [comment]
Wow @mackron! Many thanks for the big update!

It seems there is some issue on Android compilation:
```
cd /home/travis/build/raysan5/raylib/build/release && /tmp/android-toolchain/bin/aarch64-linux-android-clang -DANDROID -DGRAPHICS_API_OPENGL_ES2 -DPLATFORM_ANDROID -DRAYLIB_CMAKE=1 -D__ANDROID_API__=21 -Draylib_shared_EXPORTS -I/home/travis/build/raysan5/raylib/build -isystem /home/travis/build/raysan5/raylib/src/. -I/home/travis/build/raysan5/raylib/src/external/android/native_app_glue  -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -funwind-tables -ffunction-sections -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  -g -fPIC   -std=gnu99 -o CMakeFiles/raylib_shared.dir/external/mini_al.c.o   -c /home/travis/build/raysan5/raylib/src/external/mini_al.c
In file included from /home/travis/build/raysan5/raylib/src/external/mini_al.c:4:
/home/travis/build/raysan5/raylib/src/external/mini_al.h:15079:5: error: 
      expected expression
    mal_bool32 cbResult = MAL_TRUE;
    ^
/home/travis/build/raysan5/raylib/src/external/mini_al.h:15082:9: error: use of
      undeclared identifier 'cbResult'
    if (cbResult) {
        ^
/home/travis/build/raysan5/raylib/src/external/mini_al.h:15086:9: error: use of
      undeclared identifier 'cbResult'
        cbResult = callback(pContext, mal_device_type_playback, &deviceI...
        ^
/home/travis/build/raysan5/raylib/src/external/mini_al.h:15090:9: error: use of
      undeclared identifier 'cbResult'
    if (cbResult) {
        ^
/home/travis/build/raysan5/raylib/src/external/mini_al.h:15094:9: error: use of
      undeclared identifier 'cbResult'
        cbResult = callback(pContext, mal_device_type_capture, &deviceIn...
```
I checked the code but I couldn't find the issue, actually, it compiles perfectly in all other platforms. Maybe related to the `goto` label?

**Comment by raysan5** [comment]
By the way @mackron, could you take a look to MP3 support? I tried to implement it with `dr_mp3` but some thing were missing.

**Comment by raysan5** [comment]
It seems after a re-launch of compilation it worked ok... weird... 

Ok, I wait for your answer to merge.

**Comment by mackron** [comment]
I have no idea off the top of my head what would cause that build error. I tested on Android Studio against API 16 and 21 and it was fine here.

What's not working with MP3?

**Comment by raysan5** [comment]
oh, ok, no worries then.

Merging changes!

**Comment by a3f** [comment]
> I checked the code but I couldn't find the issue, actually, it compiles perfectly in all other platforms. Maybe related to the goto label?

C forbids following a label directly with a declaration. I pushed a fix.

**Comment by raysan5** [comment]
wow! I didn't know that! Actually, I never used goto statements in C...

Pointing to @mackron to be aware of this issue!

**Comment by a3f** [comment]
@raysan5 You might have run into it when using switch labels as well:

```
switch (ch) {
    case 'A': int disallowed_declaration = 1;
}
```

**Comment by raysan5** [comment]
wow! I think I never run into that... but I always use brackets on switch cases... ;)

**Comment by mackron** [comment]
Thanks @a3f. I've fixed this upstream.

**Pull request merged**
