### PR TITLE
Improve gltf support

### PR DESCRIPTION
**Pull request by object71**
Linked to #1639 

- Fixed model loading for the raylib logo (because it had inidicies in whole INTs and not shorts as raylib expects them)
- Animated triangle doesn't crash the program (because it doesn't have normals)

General improvements:

- Removed accessor read macro and replaced it with a function for reading values from an accessor (same function I intruduced for loading gltf animations)
- Split bigger sections from the load gltf model function into an appropriate functions for easier maintainability.
- Added support for loading int type vertices and normals.

Models still not working:

image

- GearboxAssy.glb is still not being loaded correctly and needs improvement before we close the issue.
- Support for morph animations can be considered as another issue.

@raysan5 Please take a look and see if you want something renamed or set up differently. I prefer to commit on a more managable chunks so I prefer to commit this and continue with fixing the GearboxAssy later when I have time or let someone else have a go. :)

### CODE REVIEW

**Comment by raysan5** [comment]
@object71 Oh, sorry, just seen the PR while working on some big changes (commit https://github.com/raysan5/raylib/commit/01e28263be9869b28acae5cf1128472269626edb). Please, could you review the conflicts before integration?

**Comment by object71** [comment]
Yeah, just resolving the conflicts :) Be ready in a minute

**Comment by object71** [comment]
@raysan5 I merged it but wait for all the checks still.

**Comment by raysan5** [comment]
@object71 Merged! Thank you very much for the improvement! I'll review the functions name if I find it convenient.

**Pull request merged**
