### PR TITLE
Add the remaining numeric keypad keys, and a few other missing ones

### PR DESCRIPTION
**Pull request by justinclift**
Follows on from #628. :smile:

### CODE REVIEW

**Comment by justinclift** [comment]
k, now it's good.  Just had to rename one of the new key definitions (copied from GLFW), as an existing android key already took it's name.  Fixed now. :wink:

**Comment by justinclift** [comment]
Looking at that Travis CI failure, it seems to be a problem with the Travis infrastructure during that run:

```
0.00s$ mkdir build
0.10s$ $RUNNER $CC --version
aarch64-linux-android-clang: command not found
The command "$RUNNER $CC --version" failed and exited with 127 during .
```

Is it feasible to re-run the check?

**Comment by justinclift** [comment]
Ahhh, I can probably just re-push the commit with a slightly changed commit date.  That should trigger a re-run. :smile:

**Comment by raysan5** [comment]
Merged! Thanks for the improvement! :)

@justinclift I've seen you've trying the VR Simulator in Go, do you think same improvements are required here?

**Comment by justinclift** [comment]
Just looked at it... it'd probably make sense to do so.  The screen width/height info is in the `VRDeviceInfo` structure anyway so might as well use it. :smile:

That'd probably also make it easier for people to switch to a new device too.  eg just change the one it's using, which will then automatically grab the relevant bits.

Want me to make a PR?  It's a pretty simple change. :smile:

**Comment by raysan5** [comment]
Let me check it more carefully before the PR... :)

**Comment by justinclift** [comment]
Yeah, it's probably something you could do easily, and likely better. :smile:

**Pull request merged**
