### PR TITLE
Add support for opengl 2.1

### PR DESCRIPTION
**Pull request by dvolk**
Adds the ability to use shaders on older hardware.

### CODE REVIEW

**Comment by raysan5** [comment]
Hi @dvolk, thank you very much for the update. Unfortunately, latest raylib version is being developed on [develop](https://github.com/raysan5/raylib/tree/develop) branch and it's quite far ahead `master` branch. GLEW dependency is being completely removed and replaced by GLAD and support for older versions of OpenGL was not planned. Actually, I was planning to remove support for OpenGL 1.1 at some point (current drivers just translate it automatically to latest version supported by the graphic card).

Why do you need OpenGL 2.1? Are you using it for any specific platform? Maybe Raspberry Pi desktop?

**Comment by dvolk** [comment]
Oh, I see. Can GLAD work with 2.1?

I have an old laptop that only supports 2.1 so I thought it'd be neat to have it.

**Comment by raysan5** [comment]
Hi @dvolk, [GLAD](https://github.com/Dav1dde/glad) should work ok with OpenGL 2.1; included version is for OpenGL 3.3 but I think it should work.

On the other hand, raylib only uses a small set of OpenGL 3.3 functions and tracks VAO support to use only VBOs in case no VAOs supported. It should work with OpenGL 2.1 with only some small tweaks...

Supporting old hardware is always tricky because it implies additional conditions to check and additional code to maintain so I decided to just stuck with OpenGL 1.1 for older devices and OpenGL 3.3 for current ones. It's true that shaders support is not available on OpenGL 1.1 but adding support for OpenGL 2.1 also implies adding support for GLSL version 120...

**Comment by dvolk** [comment]
Well if you like I can work on it.

I don't know completely how different GLSL 120 and 330 are. For simple programs it seems it's just the way in/out variables are specified, so it shouldn't be much trouble.

**Comment by raysan5** [comment]
`GLSL 120` is similar to `GLSL 100` used on `GRAPHICS_API_OPENGL_ES2`. The only change required is `#version 100` to `#version 120` and removing the `precision mediump float;` line in the fragment shader.

Supporting OpenGL 2.1 is not much trouble but I feel it adds unnecessarily complexity to the library instead of simplifying it. A really small segment of potential raylib users require this capability.

**Comment by dvolk** [comment]
Raylib with the ES target does not build for me. I assumed it didn't work on desktops.

**Comment by raysan5** [comment]
`GRAPHICS_API_OPENGL_ES2` is intended for Android, Raspberry Pi and HTML5 platforms, it could work on desktop using `WGL_EXT_create_context_es2_profile` extension because OpenGL ES 2.0 is essentially a stripped-down version of OpenGL 2.0 with a few added features... but raylib is not considering that case (again, it implies some tweaks and redesign).

The way you implemented it in this push-request was mostly right, it only required:
 - To be done in current raylib [develop](https://github.com/raysan5/raylib/tree/develop) branch
 - Replace GLEW extensions initialization by GLAD extensions initialization (crossing fingers)
 - Review internal shader conditions

**Comment by dvolk** [comment]
Gotcha. So you would accept that?

**Comment by raysan5** [comment]
Ok, I would accept the update... just wait a bit (one week) because rlgl module is being highly modified right now, to avoid conflicts.

Again, thank you very much for your addition.

**Comment by dvolk** [comment]
Great! I'm travellng anyway at the moment so I don't have much time.

**Comment by raysan5** [comment]
Hi @dvolk, if you can send me the changes commented in this thread I will integrate them in the develop branch. Thanks! :)

**Comment by dvolk** [comment]
I started on this, but the develop branch doesn't build for me

```
dv@laptop:~/src/lib/raylib/src$ git log | head -3
commit 60232810d83c7ea3a52491f0b20444003be53358
Author: raysan5 <raysan5@gmail.com>
Date:   Fri Jun 3 19:00:58 2016 +0200
dv@laptop:~/src/lib/raylib/src$ make clean && make
rm -f *.o libraylib.a
Cleaning done
gcc -c core.c -O1 -Wall -std=gnu99 -fgnu89-inline -Wno-missing-braces -I. -I../src -I../external/glfw3/include -I../external/openal_soft/include -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_11
core.c: In function ‘InitDisplay’:
core.c:1723:28: warning: unused variable ‘modes’ [-Wunused-variable]
         const GLFWvidmode *modes = glfwGetVideoModes(glfwGetPrimaryMonitor(), &count);
                            ^
core.c: In function ‘StorageLoadValue’:
core.c:1091:13: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(&value, 1, 4, storageFile);
             ^
gcc -c rlgl.c -O1 -Wall -std=gnu99 -fgnu89-inline -Wno-missing-braces -I. -I../src -I../external/glfw3/include -I../external/openal_soft/include -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_11
rlgl.c: In function ‘SetMatrixProjection’:
rlgl.c:2256:5: error: ‘projection’ undeclared (first use in this function)
     projection = proj;
     ^
rlgl.c:2256:5: note: each undeclared identifier is reported only once for each function it appears in
rlgl.c: In function ‘SetMatrixModelview’:
rlgl.c:2262:5: error: ‘modelview’ undeclared (first use in this function)
     modelview = view;
     ^
Makefile:122: recipe for target 'rlgl.o' failed
make: *** [rlgl.o] Error 1
```

**Comment by raysan5** [comment]
Ouch! I see, a couple of changes I did two days ago... 
I'll correct it today when I get home (in about 4-5 hours).

Thanks for pointing it out! :)

**Comment by raysan5** [comment]
Ok, develop branch updated.

**Comment by raysan5** [comment]
Checking the required changes to introduce OpenGL 2.1 support, I realized that it can be extremely simplified to the following lines at beginning of rlgl.c:
```c
#if defined(GRAPHICS_API_OPENGL_21)
    #define GRAPHICS_API_OPENGL_33
#endif
```
That way, won't be required to append `|| defined(GRAPHICS_API_OPENGL_21)` everywhere; most of the functionality used for OpenGL 3.3 is actually introduced in OpenGL 2.1.

Obviously, in some code points it would be required to check for `GRAPHICS_API_OPENGL_21`... basically, on default shader definition.

**Comment by dvolk** [comment]
The examples load resources/shaders/standard.vs and resources/shaders/standard.fs, which fall back to the default shaders when they fail to load. The default shaders don't seem to render fonts any more though.

Also I'm not sure what causes the standard shader to be used in the examples.

**Comment by raysan5** [comment]
Ouch! Yes, that part needs redesign... One of the additions for next raylib version i support for materials and lighting; it is accomplished using a standard shader (right now placed in resources/shaders/ folder).

Standard shader loading is done [here](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c#L2576) and this function is called at raylib initialization, 

Standard shader needs to be embed into raylib (similar to default shader) and also adapted for every version of GLSL (100, 120, 330). It's also planned to do a lazy initialization for the shader (only if it is used).

Fallback to default shader was not properly implemented, I just added it right now.

**Comment by raysan5** [comment]
Ok, I just finished everything I post a while ago... Standard shader hasn't been tested yet on OpenGL ES 2.0, most probably some functions are not supported... Need to review it, I'll try to do it tomorrow...

**Comment by dvolk** [comment]
On 2.1 at least, there's no inverse(mat3), so that's going to be interesting.

**Comment by raysan5** [comment]
Here it is some info: 
    http://stackoverflow.com/questions/22643604/glsl-es-2-0-inverse-matrix
    https://github.com/dsheets/gloc/blob/master/stdlib/matrix.glsl
    https://www.opengl.org/discussion_boards/showthread.php/197633-Help-converting-from-glsl-400-to-130

I'll take a look ASAP.

**Comment by raysan5** [comment]
Shader has been adapted by @victorfisac on pull request https://github.com/raysan5/raylib/pull/128

**Comment by raysan5** [comment]
Hi @dvolk, did you take a look to this issue? Does it work for you now?

**Comment by dvolk** [comment]
I gave it a try but I can't get it to load the standard shader. Something's lost in the soup of #defines.

Here's the diff: http://pastebin.com/raw/uhxEyJyT

**Comment by raysan5** [comment]
Ok, I'll try to update my code to support OpenGL 2.1.

**Comment by raysan5** [comment]
Support for OpenGL 2.1 implemented in commit https://github.com/raysan5/raylib/commit/4df7a0f2f8cf5c4dde236bd99d05d83c7b472db5

Please, @dvolk, could you verify it works? In my PC it works ok.

**Comment by dvolk** [comment]
It builds and the examples run, but all of the games are broken (many elements don't show, no errors).

Also is there an example that's supposed to load the standard shader? Because looking at the log they're only loading the default shader (+ some load extra from files).

So this might have the same problem I had.

**Comment by raysan5** [comment]
Ok, now everything should work, I corrected some issues on commit https://github.com/raysan5/raylib/commit/9fdf4420d5354c32394246703015a686df8135ce

To test the standard shader, you should use example: [shaders_standard_lighting](https://github.com/raysan5/raylib/blob/develop/examples/shaders_standard_lighting.c).

**Comment by dvolk** [comment]
Oh, I didn't have that one to test because an example before it fails to build.

```
dv@laptop:~/src/lib/raylib/examples$ make
gcc -o audio_music_stream audio_music_stream.c -O2 -Wall -std=c99 -I. -I../src -I/usr/local/include/raylib/ -L. -L../../src -lraylib -lglfw -lGL -lopenal -lm -pthread -ldl -lX11 -lXrandr -lXinerama -lXi -lXxf86vm -lXcursor -DPLATFORM_DESKTOP 
audio_music_stream.c: In function ‘main’:
audio_music_stream.c:27:21: warning: passing argument 1 of ‘PlayMusicStream’ makes integer from pointer without a cast [-Wint-conversion]
     PlayMusicStream("resources/audio/guitar_noodling.ogg");         // Play music stream
                     ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:879:5: note: expected ‘int’ but argument is of type ‘char *’
 int PlayMusicStream(int index, char *fileName);                 // Start music playing (open stream)
     ^
audio_music_stream.c:27:5: error: too few arguments to function ‘PlayMusicStream’
     PlayMusicStream("resources/audio/guitar_noodling.ogg");         // Play music stream
     ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:879:5: note: declared here
 int PlayMusicStream(int index, char *fileName);                 // Start music playing (open stream)
     ^
audio_music_stream.c:61:34: error: too few arguments to function ‘PauseMusicStream’
         if (IsWindowMinimized()) PauseMusicStream();
                                  ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:882:6: note: declared here
 void PauseMusicStream(int index);                               // Pause music playing
      ^
audio_music_stream.c:62:14: error: too few arguments to function ‘ResumeMusicStream’
         else ResumeMusicStream();
              ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:883:6: note: declared here
 void ResumeMusicStream(int index);                              // Resume playing paused music
      ^
audio_music_stream.c:64:22: error: too few arguments to function ‘GetMusicTimePlayed’
         timePlayed = GetMusicTimePlayed()/GetMusicTimeLength()*100*4; // We scale by 4 to fit 400 pixels
                      ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:887:7: note: declared here
 float GetMusicTimePlayed(int index);                            // Get current music time played (in seconds)
       ^
audio_music_stream.c:64:43: error: too few arguments to function ‘GetMusicTimeLength’
         timePlayed = GetMusicTimePlayed()/GetMusicTimeLength()*100*4; // We scale by 4 to fit 400 pixels
                                           ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:886:7: note: declared here
 float GetMusicTimeLength(int index);                            // Get current music time length (in seconds)
       ^
audio_music_stream.c:66:9: error: too few arguments to function ‘UpdateMusicStream’
         UpdateMusicStream();        // Update music buffer with new stream data
         ^
In file included from audio_music_stream.c:14:0:
../src/raylib.h:880:6: note: declared here
 void UpdateMusicStream(int index);                              // Updates buffers for music streaming
      ^
Makefile:421: recipe for target 'audio_music_stream' failed
make: *** [audio_music_stream] Error 1

```

**Pull request closed without merging**
