### PR TITLE
[raudio] Fix crash when switching playback device

### LINKED ISSUE #3743: [raudio] Crash when changing playback device
### Issue description

Example (audio_sound_loading.c) crashes when changing playback device,.

### Environment

This happens on Windows.

<details><summary>Initialization Logs</summary>

INFO: Initializing raylib 5.1-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1600 x 900
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 230
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Intel(R) UHD Graphics
INFO:     > Version:  3.3.0 - Build 27.20.100.8190
INFO:     > GLSL:     3.30 - Build 27.20.100.8190
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: ASTC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / WASAPI
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  1440
INFO: FILEIO: [resources/sound.wav] File loaded successfully
INFO: WAVE: Data loaded successfully (44100 Hz, 16 bit, 1 channels)
INFO: FILEIO: [resources/target.ogg] File loaded successfully
INFO: WAVE: Data loaded successfully (22050 Hz, 16 bit, 2 channels)
INFO: TIMER: Target time per frame: 16.667 milliseconds

</details> 

Also note that miniaudio has a similar example (`simple_playback.c`) that doesn't have an issue with switching playback devices.

### Issue Screenshot

https://github.com/raysan5/raylib/assets/7282243/6cebb61c-ec89-41f9-86df-b666491a1881

### Code Example

This happened to me on some personal projects and happens with the `audio_sound_loading` example.

### PR DESCRIPTION
**Pull request by jkaup**
Resolves #3743

### CODE REVIEW

**Comment by raysan5** [comment]
@jkaup those reviews should be pushed to miniaudio repo, not raylib, but probably @mackron is already aware of that potential issue.

**Comment by karl-zylinski** [comment]
I put in two comments with what I did when I fixed this myself.
1. I fetch the return value of `ma_CoInitializeEx` and store in a HRESULT and then check that one before uniniting. I do not know if this is needed.

2. Because (1) uses windows specific stuff I also added the MA_WIN32 things checks. The crashes only happen for me on Windows anyways, so maybe best to only do these workaround there?

Like I said, I'm not sure if you need to do those extra things I did. Other then that it looks like the same thing I did to fix the crashes.

**Comment by raysan5** [comment]
@veins1 Nice! Thanks for reporting! 

@jkaup Please, could you update this PR as per the latest comment? It seems only `ma_context_get_MMDevice__wasapi()` should be modified.

**Comment by mackron** [comment]
Thanks team, and sorry for my silence.

When the device changes, WASAPI fires a callback from a separate thread. What I suspect is happening is that COM is not being initialized on that callback thread which is then resulting in this issue. If the COM initialization was moved to the `ma_IMMNotificationClient_*` callbacks I suspect that would also address the issue. However, since multiple people have confirmed the proposed fix works, and I'm planning on refactoring the WASAPI backend anyway, I'm happy enough to get that merged upstream. It would be good if @veins1 suggestion could be confirmed though just to reduce the amount of COM sitting around in the code base.

**Comment by jkaup** [comment]
Thanks for the input on the issue @veins1 and @mackron. I will make the changes as proposed by @raysan5 as soon as possible.

**Comment by jkaup** [comment]
Hi @raysan5 , sorry, got back to work today at last. I've updated the PR so that the proposed fix only affects `ma_context_get_MMDevice__wasapi()`, and have confirmed that this is enough to fix the crash as noted by @veins1 .

**Comment by raysan5** [comment]
@jkaup nice! thanks for the review! 👍😄

**Comment by mackron** [comment]
@jkaup Thanks a lot for this. @raysan5 This has been integrated upstream in the dev branch.

**Comment by raysan5** [comment]
@mackron that's great! planning to update miniaudio library soon! 👍😄

**Pull request merged**
