### PR TITLE
build.zig: Fix `@src` logic and a few things

### PR DESCRIPTION
**Pull request by sagehane**
Motivation and context:
https://github.com/raysan5/raylib/pull/4375#issuecomment-2408950056
https://github.com/raysan5/raylib/pull/4375#issuecomment-2408998315

@Not-Nik, I'm pretty sure this works but can you check just in case?

### CODE REVIEW

**Comment by raysan5** [comment]
@sagehane Thank you very much for the quick review!

**Comment by sagehane** [comment]
@raysan5, very embarrassing, I fixed a small logic error, made a commit, then noticed I forgot to type some stuff and totally forgot that I never fixed that part. Is it possible to revert and have https://github.com/sagehane/raylib/commit/81691c66a0b34328810395d914e31d20386841bc merged? The only change is line 68. Again, very embarrassing.

**Comment by raysan5** [comment]
@sagehane No problem. Please, could you send another PR with the required fixes?

**Comment by rstefanic** [comment]
I just updated raylib in an existing Zig project and the project now fails to build.

raylib fails to build as a submodule now because it's looking for the source files in the wrong directory.

```
error: unable to check cache: stat file '/Users/robert/Code/Repositories/rglfw.c' failed: FileNotFound
```

That's the wrong directory as it's a general directory where I keep my projects – makes sense why it can't find the file there! The project directory that I'm running the build from is `/Users/robert/Code/Repositories/<project>` and raylib is a submodule in `/Users/robert/Code/Repositories/<project>/libs/raylib`.

The reason why it's looking in the wrong place stems from this line added in this PR.

[    const src_file = std.fs.path.relative(b.allocator, @src().file, ".") catch @panic("OOM");](https://github.com/raysan5/raylib/blob/c9c830cb971d7aa744fe3c7444b768ccd5176c4c/src/build.zig#L71)

This line is evaluating to `../../..` in my build. That explains why it's walking up three directories to look for the raylib source files, but that's not where they are. 😆 

For the time being, I've just rolled back the commit before the changes to `build.zig` were introduced several days ago.

As a side note, this library rules. Thank you so much for it. ✌️

**Comment by rstefanic** [comment]
I created a repo to reproduce the issue. You can follow the commit logs to see the exact steps that I took. Reverting to an a commit before the recent changes made to `build.zig` works as expected. The README in this repo has a quick commit hash you can use to checkout a version of raylib where it works.

https://github.com/rstefanic/raylib-zig-build-bug

**Comment by sagehane** [comment]
I'm so sorry, I was far too sleepy when I wrote that. My guess is that this is the correct code:
```diff
diff --git a/src/build.zig b/src/build.zig
index 40a506fd..b3ba43cd 100644
--- a/src/build.zig
+++ b/src/build.zig
@@ -69,7 +69,7 @@ fn srcDir(b: *std.Build) []const u8 {
             @compileError("Please take a look at this function again");
     }
 
-    const src_file = std.fs.path.relative(b.allocator, @src().file, ".") catch @panic("OOM");
+    const src_file = std.fs.path.relative(b.allocator, ".", @src().file) catch @panic("OOM");
     return std.fs.path.dirname(src_file) orelse ".";
 }
```
I'll try to test it with your repo.

**Pull request merged**
