### PR TITLE
add api FIFO based character input.

### PR DESCRIPTION
**Pull request by Ushio**
Hi, I created the following APIs about https://github.com/raysan5/raylib/issues/535

```
RLAPI bool HasWaitingInputCharacter();                        // Check if input character exists at least one in the internal input character stream. The characters are produced by the operating system text input system.
RLAPI unsigned int PullNextInputCharacter();                  // Pull a input character from the the internal input character stream
```

It can handle multiple characters per frame. 
This is the example which modified from "raylib [text] example - Input Box"

```
/*******************************************************************************************
*
*   raylib [text] example - Input Box
*
*   This example has been created using raylib 1.7 (www.raylib.com)
*   raylib is licensed under an unmodified zlib/libpng license (View raylib.h for details)
*
*   Copyright (c) 2017 Ramon Santamaria (@raysan5)
*
********************************************************************************************/

#include "raylib.h"

#define MAX_INPUT_CHARS     9

int main(void)
{
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;

    InitWindow(screenWidth, screenHeight, "raylib [text] example - input box");

    char name[MAX_INPUT_CHARS + 1] = "\0";      // NOTE: One extra space required for line ending char '\0'
    int letterCount = 0;

    Rectangle textBox = { screenWidth/2 - 100, 180, 225, 50 };
    bool mouseOnText = false;

    int framesCounter = 0;

    SetTargetFPS(10);               // Set our game to run at 10 frames-per-second for test
    //--------------------------------------------------------------------------------------

    // Main game loop
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        if (CheckCollisionPointRec(GetMousePosition(), textBox))
        {
        	mouseOnText = true;
        }
        else
        {
        	mouseOnText = false;
        }
        
        while (HasWaitingInputCharacter())
        {
        	unsigned int key = PullNextInputCharacter();
        
        	// NOTE: Only allow keys in range [32..125]
        	if (mouseOnText && (key >= 32) && (key <= 125) && (letterCount < MAX_INPUT_CHARS))
        	{
        		name[letterCount] = (char)key;
        		letterCount++;
        	}
        }

        if (mouseOnText)
        {
            if (IsKeyPressed(KEY_BACKSPACE))
            {
                letterCount--;
                name[letterCount] = '\0';

                if (letterCount < 0) letterCount = 0;
            }
        }

        if (mouseOnText) framesCounter++;
        else framesCounter = 0;
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        BeginDrawing();

            ClearBackground(RAYWHITE);

            DrawText("PLACE MOUSE OVER INPUT BOX!", 240, 140, 20, GRAY);

            DrawRectangleRec(textBox, LIGHTGRAY);
            if (mouseOnText) DrawRectangleLines(textBox.x, textBox.y, textBox.width, textBox.height, RED);
            else DrawRectangleLines(textBox.x, textBox.y, textBox.width, textBox.height, DARKGRAY);

            DrawText(name, textBox.x + 5, textBox.y + 8, 40, MAROON);

            DrawText(FormatText("INPUT CHARS: %i/%i", letterCount, MAX_INPUT_CHARS), 315, 250, 20, DARKGRAY);

            if (mouseOnText)
            {
                if (letterCount < MAX_INPUT_CHARS)
                {
                    // Draw blinking underscore char
                    if (((framesCounter/20)%2) == 0) DrawText("_", textBox.x + 8 + MeasureText(name, 40), textBox.y + 12, 40, MAROON);
                }
                else DrawText("Press BACKSPACE to delete chars...", 230, 300, 20, GRAY);
            }

        EndDrawing();
        //----------------------------------------------------------------------------------
    }

    // De-Initialization
    //--------------------------------------------------------------------------------------
    CloseWindow();        // Close window and OpenGL context
    //--------------------------------------------------------------------------------------

    return 0;
}


```

## limitations

But it is not perfect because a operating system IME conversion sometimes generates so many texts while one frame. But it needs more complicated implementations to make perfect.
I think the perfect one is too much.

Additionally, the Backspace key also sometimes lost at the lower framerate. But it is also hard to fix.

### CODE REVIEW

**Comment by Ushio** [comment]
About renaming "GetKeyPressed" to "GetCharPressed", 
Should I rename the raylib.c.tags, c_raylib.xml, raylib_npp.xml, raylib_to_parses.h?
It seems auto-generated files but I didn't figure out the details.

rename

**Comment by raysan5** [comment]
@Ushio Thank you very much for this implementation! It was a long time pending issue... 

As we discussed in Discord, it could require some renaming... Just excuse me because I'm very busy lately and it could take a while before reviewing it... :)

**Comment by Ushio** [comment]
Thanks, It is ok. Please take care of your important time.
And I replaced the tab to white space x4.

**Comment by raysan5** [comment]
@Ushio Thank you very much for working on this issue! Just merging and reviewing it! :)

**Comment by raysan5** [comment]
Just reviewed it to keep original API for the moment.
Also reviewed implementation for other platforms.

**Pull request merged**
