### PR TITLE
implement transformation and projection stacks

### PR DESCRIPTION
**Pull request by mgood7123**
this allows for separate transformation and projection stacks and addresses the core issue stated in https://github.com/raysan5/raylib/pull/2146

### CODE REVIEW

**Comment by raysan5** [comment]
This is a good improvement of current implementation but a Matrix stack does seem a feature more aligned with legacy OpenGL style API than new graphics APIs... for the moment, I'm not merging this improvement.

**Comment by mgood7123** [comment]
> This is a good improvement of current implementation but a Matrix stack does seem a feature more aligned with legacy OpenGL style API than new graphics APIs... for the moment, I'm not merging this improvement.

true, tho this is mainly to remain compatible with a core legacy OpenGL feature that is present when using raylib with legacy OpenGL but absent when using raylib with modern OpenGL

simply so RayLib can remain compatible with both legacy OpenGL and modern OpenGL without rewriting code (most modern GL users implement their own matrix stacks anyway so this just makes it easier)

**Comment by raysan5** [comment]
I know... but I don't know how long the OpenGL 1.1 backend will be kept as an option. Current matrix implementation is not perfect it's probably more than enough for users targeting OpenGL 1.1 in 2022.

**Comment by mgood7123** [comment]
> I know... but I don't know how long the OpenGL 1.1 backend will be kept as an option. Current matrix implementation is not perfect but it's probably more than enough for users targeting OpenGL 1.1 in 2022.

true, gl 1.1 is quite old

**Comment by mgood7123** [comment]
maybe the matrix stack can be optional?

**Pull request closed without merging**
