### PR TITLE
Expose FBO aspect

### PR DESCRIPTION
**Pull request by pfeodrippe**
So we can customize the 3d mode if desired.

### CODE REVIEW

**Comment by pfeodrippe** [comment]
For more context (and an example), I'm using this to read GLTF metadata and set the Camera rotation \o Let me know if this is okay.

**Comment by raysan5** [comment]
@pfeodrippe Is it possible to do the same with `GetRenderWidth()` and `GetRenderHeight()`? I would prefer to avoid adding this specific function.

**Comment by pfeodrippe** [comment]
Hi @raysan5, if you say that you could use GetRenderWidth and GetRenderHeight at https://github.com/raysan5/raylib/blob/f1007554a0a8145060797c0aa8169bdaf2c1c6b8/src/rcore.c#L989 instead of referring to currentFbo, then yes, let me know if this will always be correct.  

Thank you very much for the lib and review :D

**Comment by pfeodrippe** [comment]
@raysan5 So are they the same thing based on your 👍 ? Can we use, for example, CORE.Window.currentFbo.width and GetRenderWidth() interchangeably?

**Comment by raysan5** [comment]
@pfeodrippe Afaik, there could be a difference when using RenderTextures but it should be analized more carefully. Still, I prefer not to expose the function on its current form. In any case, I'd prefer to update render size for RenderTexture if requried.

**Comment by pfeodrippe** [comment]
> @pfeodrippe Afaik, there could be a difference when using RenderTextures but it should be analized more carefully. Still, I prefer not to expose the function on its current form. In any case, I'd prefer to update render size for RenderTexture if requried.

Thanks o/

**Pull request closed without merging**
