### PR TITLE
examples: core: adds 2D camera two player split screen

### LINKED ISSUE #3294: [examples] split screen for 2D camera
I see that there is a 3D splitscreen example (examples/core/core_split_screen.c)

Is there an example for a 2D split screen?

### PR DESCRIPTION
**Pull request by gabrielssanches**
closes #3294

Polishes code written by @raysan5 in issue #3294 
- adds camera tracking on each player
- adds grid

### CODE REVIEW

**Comment by raysan5** [comment]
The example addition actually requires some reviews:

 - Name should be `core_camera_2d_split_screen`
 - A screenshot is required with same name, use F12 to take it
 - Example should be added to examples Makefile
 - Example should be added to VS2022 project

**Comment by gabrielssanches** [comment]
> The example addition actually requires some reviews:
> 
>     * [ ]  Name should be `core_camera_2d_split_screen`
> 
>     * [ ]  A screenshot is required with same name, use F12 to take it
> 
>     * [ ]  Example should be added to examples Makefile
> 
>     * [ ]  Example should be added to VS2022 project

all done

**Comment by raysan5** [comment]
@gabrielssanches Great! Thank you very much for the addition! 😄

**Comment by asdqwe** [comment]
Hello,

Sorry to interject, but it would have been nice to at least mention/acknowledge https://github.com/raysan5/raylib/issues/3294#issuecomment-1706736332.

Best regards.

**Comment by raysan5** [comment]
@asdqwe You are right, I didn't noticed it. Actually I reviewed the example to add @gabrielssanches as the contributor. @ubkp please, feel free to send a PR adding you to the header info.

**Comment by ubkp** [comment]
@raysan5 No need, I don't mind. It's ok. :+1:

**Comment by gabrielssanches** [comment]
> Hello,
> 
> Sorry to interject, but it would have been nice to at least mention/acknowledge [#3294 (comment)](https://github.com/raysan5/raylib/issues/3294#issuecomment-1706736332).
> 
> Best regards.

my bad,  was too fast copying the code and forgot to mention you

**Pull request merged**
