### PR TITLE
Fix rcamera.h issues

### PR DESCRIPTION
**Pull request by ubkp**
This PR address part of _"REVIEW: Example: core_3d_camera_free. Displayed controls do not match and camera behaves strangely."_ from https://github.com/raysan5/raylib/discussions/2952.

1. Fixes `CAMERA_FREE` behaving strangely (unintended rolling while yawing and pitching) by setting `rotateUp` to `false` ([R439](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R439)). This change does not impact the other cameras, because `rotateUp` is already `false` for them.

2. Fixes `CAMERA_FREE` mouse wheel zoom by adding it to the zoom mode check ([R503](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R503)).

3. Adds pan to `CAMERA_FREE` by adding handling for it before mouse and keyboard handling ([R462-R472](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R462-R472)) and a define for `CAMERA_PAN_SPEED` ([R187](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R187)).

4. Readds up (`Space`) and down (`Left Ctrl`) movement to `CAMERA_FREE` ([R496-R500](https://github.com/raysan5/raylib/pull/3240/files#diff-cb37d550d2b398139f0ed2cebf04598776b16fa58107b4b4b7b7099280a67db5R496-R500)). This change does not impact the other cameras because it was already disabled for them.

Tested these proposed changes successfully on `PLATFORM_DESKTOP` on Linux (Linux Mint 21.1 x86_64) and `PLATFORM_WEB`.

**Edit:** added line marks.

### CODE REVIEW

**Comment by raysan5** [comment]
@ubkp Nice! Thank you very much for the improvement! :)

**Comment by ubkp** [comment]
@raysan5 Still on this topic, the `core_3d_camera_free` displayed control mentions _"Alt + Mouse Wheel Pressed to Rotate"_ ([L74](https://github.com/raysan5/raylib/blob/master/examples/core/core_3d_camera_free.c#L74)), but I don't understand this one. Isn't that the same as just moving the mouse? Do you remember what it meant by that?

**Comment by raysan5** [comment]
@ubkp Mouse wheel was possible to be pressed as an additional button, actually the control scheme was the same one used by 3d max and other 3d softwares to navigate the scene.

In any case, camera does not necessarily follow those controls, new ones could be added and the text changed for consistency.

**Comment by ubkp** [comment]
@raysan5 Got it. Thank you very much for the explanation.

**Pull request merged**
