### PR TITLE
[raymath] Clang Vector Extension support

### PR DESCRIPTION
**Pull request by jopadan**
- Replace src/raymath.h Vector type definitions with ext_vector_type ones for clang compiler to activate use
`cmake -DCMAKE_C_COMPILER=clang`
- silence example type cast warning

**TODO**
- check for Vector3 storage size change from 12 to 16 bytes complications

### CODE REVIEW

**Comment by raysan5** [comment]
@jopadan Did you benchmark the benefits of this change with some sample code?

It seems interesting but I'm concerned of the potential implications of this change. `raymath` is a base library for raylib, used by multiple modules.

**Comment by raysan5** [comment]
I'm afraid the changes volume is too high and too risky for merging, just to consider a specific compiler.

**Comment by orcmid** [comment]
My impression is that compiler command-line optimization options are a better way to rely on particular hardware capabilities and also deal with their conditional presence at run-time.

The use of data structures that are recognized as optimizable are a limitation that might distort the source code and operation in the absence of actual special hardware features though.

We have enough to deal with concerning platform differences and surrendering to compiler differences sort of flies in the face of the idea that a feature of C Language is portability across platforms.

In any case, I favor the conclusion of @raysan5

**Comment by jopadan** [comment]
For benchmark results see #4486 and continue this PR topic there

**Pull request closed without merging**
