### PR TITLE
[rlgl] Reviewed `rlActiveDrawBuffers` for OpenGL ES 3

### PR DESCRIPTION
**Pull request by Bigfoot71**
see: https://github.com/raysan5/raylib/issues/4604

### CODE REVIEW

**Comment by asdqwe** [comment]
FYI, this change can be tested with the [shaders/shaders_deferred_render.c](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_deferred_render.c) example (which I think is the only example using [rlActiveDrawBuffers](https://github.com/search?q=repo%3Araysan5%2Fraylib%20rlActiveDrawBuffers&type=code)). Tested successfully on Linux Mint 22.0, LGTM.

**Comment by Bigfoot71** [comment]
@asdqwe I got this on desktop:
```
WARNING: FBO: [ID 1] Framebuffer has incomplete attachment
WARNING: Framebuffer is not complete
```

Setup (Linux Mint 21.3):
```
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce GTX 980/PCIe/SSE2
INFO:     > Version:  OpenGL ES 3.2 NVIDIA 535.183.01
INFO:     > GLSL:     OpenGL ES GLSL ES 3.20
```

However, I will conduct the tests on Android in a while.

**Comment by Bigfoot71** [comment]
Well, after adapting the shaders of [shaders/shaders_deferred_render.c](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_deferred_render.c) on Android, I get the same issue:
```
 W  FBO: [ID 1] Framebuffer has incomplete attachment
 W  Framebuffer is not complete
 ```

This is something that will need to be investigated before considering merging this PR...

**Comment by asdqwe** [comment]
@Bigfoot71 https://github.com/raysan5/raylib/issues/4604#issuecomment-2543829132

**Comment by raysan5** [comment]
Merging the change, no idea what's the issue with the incomplete framebuffer.

**Comment by Bigfoot71** [comment]
@raysan5 no problem, I was planning to investigate it, I would do it within the week

**Pull request merged**
