### PR TITLE
Allow instanced rendering without a custom shader

### PR DESCRIPTION
**Pull request by TibboddiT**
This PR enables the use of `DrawMeshInstanced` without necessitating a custom shader.

It seems to me that this is inline with 

> raylib is SIMPLE and EASY-TO-USE

A secondary default shader has been introduced. This shader includes a new attribute that stores instance transformation and is loaded and managed exactly like the initial shader. It is then used in `DrawMeshInstanced`.

To avoid any breaking change, if the material's linked shader is not the defaut shader, it will be used in place of the default instanced rendering shader, preserving previous behavior.

My use case: I need to draw a few million cubes for a simulation project, and wanted to try instanced rendering capabilities of raylib. I was disappointed when I realised that a custom shader was needed, but impressed enough by the project to eventually send a PR :)

### CODE REVIEW

**Comment by ubkp** [comment]
Out of curiosity, what's the issue of using a custom shader to warrant this change?

**Comment by TibboddiT** [comment]
I just needed to draw the same mesh in a lot of different positions. I admit that writing a shader is not very complex, but not having to write one makes raylib even easier to use! Also, I noticed a lot of raylib examples on the web avoid using custom shaders, which leads me to the conclusion that "beginners" prefer not to have to think about it.

**Comment by ubkp** [comment]
1. The problem is that it makes it easier by having the library to manage that for the user. On that direction, the library, trying to make everything easier, ends up having to manage everything, becoming an engine, instead of what it is, a library of a set of tools.

2. If the users are having difficulty with shaders, then I don't think this would help solving that. IMHO, it would only make them more dependent on the library implementing something for them.

3. Since there's already support for custom shaders, IMHO, I don't think this should be added.

**Comment by TibboddiT** [comment]
OK, I understand.

`DrawMesh` worked immediately, and is using a default shader. After having read [raylib-default-shader](https://github.com/raysan5/raylib/wiki/raylib-default-shader) and [raylib-generic-uber-shader-and-custom-shaders](https://github.com/raysan5/raylib/wiki/raylib-generic-uber-shader-and-custom-shaders), I thought making `DrawMeshInstanced` as easy to use as `DrawMesh` was a good idea.

Thanks for your time, and for the library. Feel free to close.

**Comment by raysan5** [comment]
@TibboddiT Thanks for the review, I'm afraid I agree with @ubkp points, actually I prefer to keep the instancing shader out of raylib, I think it's a feature most users do not need to be provided by raylib and advance users won't have a problem implementing it on user code.

Also note that users requiring instancing, could also require more data than only the `transforms` (as stated on https://github.com/raysan5/raylib/issues/3337), this feature could grow a lot and never fit exactly what an advance user needs, so I think it's better to keep it at user side (as much as possible).

**Comment by Murtagy** [comment]
I agree with the author. For some unknown reasons DrawMesh works fine, but DrawMeshInstanced does not. It is absolutely annoying to see nothing at all on the screen and seeing meshes with default shaders and knowning that a problem is likely in a shader would be way better

**Pull request closed without merging**
