### PR TITLE
BM Font Extender 

### PR DESCRIPTION
**Pull request by DongkunLee**
I want Bitmap Font loader is extended. 
This code can load multiple atlas. 

I wish may it could be helpful to raylib.

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks pretty cool. Have been curious about .bmf myself. Looks to bring in a third-party library? Perhaps it could live as an external library quite well... call if raylib-bmfont or something :)

**Comment by RobLoach** [comment]
Oh nice! That sounds really cool.

**Comment by raysan5** [comment]
@DongkunLee The following file should be removed from the PR to be able to be merged: `loadbmfontex.diff`

**Comment by raysan5** [comment]
@DongkunLee Please, could you remove the `loadbmfontex.diff` file from the PR to merge?

**Comment by raysan5** [comment]
Just reviewed the PR for merging but please note this is not the expected way to contribute to a project. The contributor must ensure the PR is correct and become the owner of its contributions.

**Pull request merged**
