### PR TITLE
Add Builder project files

### PR DESCRIPTION
**Pull request by jubalh**
Takes care of Builder for https://github.com/raysan5/raylib/issues/466

### CODE REVIEW

**Comment by a3f** [comment]
Could you remove the openAL and glfw3 dependency?

**Comment by jubalh** [comment]
@a3f why?

**Comment by a3f** [comment]
There's no need to link them in anymore. Audio is now handled by [`src/external/mini_al.h`](https://github.com/raysan5/raylib/blob/master/src/external/mini_al.h). GLFW3 is included in [`src/rglfw.c`](https://github.com/raysan5/raylib/blob/master/src/rglfw.c).

**Comment by jubalh** [comment]
@a3f I believe that is not true for 1.8.0.
openSUSE ships raylib 1.8.0, because that is the latest stable release.

My idea of a workflow is that all packages get intalled from the distribution with as less self compilation as possible. Only the game the 'user' wants to write is what he should compile, the rest should installed via the package manager.

For this reason I prefer having this in there.

**Comment by jubalh** [comment]
Added a note about it, so it can be changed later and people understand. Thanks for the hint @a3f.

**Comment by raysan5** [comment]
ok, I see both points of view, agree with @a3f that it should be removed but also with @jubalh about the latest stable release. Just integrating it (thanks for the note) and it should be updated after next official stable release.

**Pull request merged**
