### PR TITLE
Implementing GetMonitorWidth/Height for DRM

### PR DESCRIPTION
**Pull request by gabriel-marques**
Hello :)

I would like to propose an implementation for the following functions for the DRM platform : 

- int GetMonitorWidth(int monitor)
- int GetMonitorHeight(int monitor)
- int GetMonitorPhysicalWidth(int monitor)
- int GetMonitorPhysicalHeight(int monitor)
- const char *GetMonitorName(int monitor)

Although the monitor selection is not supported for the drm platform I kept the argument to avoid having multiple function prototypes.

I hope it complies to your coding rules :)

### CODE REVIEW

**Comment by colesnicov** [comment]
Hello. What would it be good for? In addition to the fact that I can find out these dimensions... At the moment we have encountered such an unpleasant dilemma regarding DRM: https://github.com/raysan5/raylib/issues/3946. Can you please tell me about it?

**Review by orcmid — CHANGES_REQUESTED** [review]
In `GetMonitorName(int monitor)`

for consistent behavior with the unimplemented case, you should use

```
const char name = "";
```

Also, to avoid many warnings about the non-zero `monitor`, you might want to do something about the non-zero value case, providing something like "unknown" or "unavailable".  This will also avoid compiler warnings about `monitor` not being used :).

It looks like it might be valuable to have a `GetMonitorCount()` or similar as part of `raylib.h` and have that always return `1` for DRM. 

Isn't there a `raylib.h` way to `GetCurrentMonitor()` or something like that?  (I am being lazy.)

**Comment by colesnicov** [comment]
I dont know yet. I just tuk here for few days. tests, tests, tests...

**Comment by gabriel-marques** [comment]
Hello @orcmid :)

Thanks for the suggested changes of consistency, I will apply them :)
By the way, there is both `GetMonitorCount()` and  `GetCurrentMonitor()` which although log that they are not implemented, returns the correct value (because the actual implementation is limited to one screen only)

```C
// Get number of monitors
int GetMonitorCount(void)
{
    TRACELOG(LOG_WARNING, "GetMonitorCount() not implemented on target platform");
    return 1;
}

// Get number of monitors
int GetCurrentMonitor(void)
{
    TRACELOG(LOG_WARNING, "GetCurrentMonitor() not implemented on target platform");
    return 0;
}
```

**Comment by raysan5** [comment]
@gabriel-marques Implementation looks good to me. Please, let me know when this PR is ready for merging!

**Comment by gabriel-marques** [comment]
Hello,

As @orcmid suggested I changed the `getMonitorName` to return "" as default and also I changed others functions to also evaluate negative monitors.

**Comment by raysan5** [comment]
@gabriel-marques Thanks! Implementation looks good to me! Merging!

**Pull request merged**
