### PR TITLE
Add SetWindowMaxSize for desktop and web

### PR DESCRIPTION
**Pull request by ubkp**
### Summary

- Adds `SetWindowMaxSize()` for both `PLATFORM_DESKTOP` and `PLATFORM_WEB`.
- Changes `SetWindowMinSize()` so it can work alongside `SetWindowMaxSize()` keeping current compatibility.
- Finishes fixing https://github.com/raysan5/raylib/issues/3231.

### Explanation

1. Adds a `windowMin` and `windowMax` member to `CORE.Window` ([R399-R400](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R399-R400)). This was necessary because although `GLFW` has a `glfwSetWindowSizeLimits()`, it doesn't have a `glfw*GET*WindowSizeLimits()` yet. And also because both `PLATFORM_DESKTOP` and `PLATFORM_WEB` needed a common dataset to be able to share the same functions.
<br>

2. Adds  `SetWindowMaxSize()` ([R1806](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1806)) that will receive an `int width` and an `int height` from the user.
3. `SetWindowMaxSize()` will then set `CORE.Window.windowMax` with those values ([R1808-R1809](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1808-R1809)).
4. Then, if it's `PLATFORM_DESKTOP`, it will `glfwSetWindowSizeLimits()` with the stored `CORE.Window.windowMin` and `CORE.Window.windowMax` values ([R1812](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1812)).
5. If it's `PLATFORM_WEB`, and `FLAG_WINDOW_RESIZABLE` is enabled, it will instead trigger the resize event so `EmscriptenResizeCallback()` can resize the canvas if necessary ([R1816](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1816)).
<br>

6. The default values of `windowMin` and `windowMax` are `GLFW_DONT_CARE` (equivalent to `-1`) ([R4247-R4251](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R4247-R4251)) and are set on `InitGraphicsDevice()` ([R4241](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R4241)). This was chosen because it integrates naturally to `glfwSetWindowSizeLimits()` and allow the resize to behave "unlimited" if no `windowMin` or `windowMax` are passed by the user.
<br>

7. Changes `SetWindowMinSize()` ([R1791](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1791)) that still receives an `int width` and an `int height` from the user, maintaining legacy compatibility.
8. `SetWindowMinSize()` now sets set `CORE.Window.windowMin` with those values ([R1793-R1794](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1793-R1794)).
9. Then, if it's `PLATFORM_DESKTOP`, it will `glfwSetWindowSizeLimits()` with the stored `CORE.Window.windowMin` and `CORE.Window.windowMax` values, like `SetWindowMaxSize()` ([R1797](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1797)).
10. If it's `PLATFORM_WEB`, and `FLAG_WINDOW_RESIZABLE` is enabled, it will instead trigger the resize event so `EmscriptenResizeCallback()` can resize the canvas if necessary ([R1801](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1801)), like `SetWindowMaxSize()`.
<br>

11. The resizing for `PLATFORM_DESKTOP` is handled as usual.
<br>

12. The resizing for `PLATFORM_WEB` is handled by `EmscriptenResizeCallback()` ([R6191](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6191)).
13. There, once it gets the `width` and `height` from `GetWindowInnerWidth()` and `GetWindowInnerHeight()` ([R6209-R6210](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6209-R6210)).
14. Then, it checks if they are smaller than the `windowMin`. If they are, it uses the `windowMin` values instead ([R6212](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6212), [R6215](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6215)).
15. If they aren't, it checks if they are larger than `windowMax` and if `windowMax` is larger than zero (necessary to handle the default `-1` value). If they are, it uses the `windowMax` values instead ([R6213](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6213), [R6216](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R6216)).
16. Otherwise, it uses the `WindowInner` values it got.

### Notes

17. Added a "temporary" `SizeInt` ([R359](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R359)) because it needed negative values (the `-1` from `GLFW_DONT_CARE`) and `Size` had `unsigned int` ([R358](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R358)).
18. Could have used a `Point` ([R357](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R357)) but `.x` and `.y` could make it harder to understand.
19. Despite https://github.com/raysan5/raylib/issues/3168#issuecomment-1703788272 I didn't want to change `Size` without asking first (I don't know if it will break something).
20. Which would be the preferable approach: `SizeInt`, `Point` or changing `Size`? @raysan5

### Testing environment

Tested this changes successfully on `PLATFORM_DESKTOP` on Linux (Mint 21.1 64-bit) and `PLATFORM_WEB` on Firefox (115.1.0esr 64-bit) and Chrome (115.0.5790.170 64-bit) both running on Linux Mint (21.1 64-bit).

### Code Example

Minimal reproduction code to test the PR:
```
#include "raylib.h"

int main(void) {
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
    InitWindow(800, 450, "test");
    SetTargetFPS(60);

    SetWindowMinSize( 200, 200);
    SetWindowMaxSize( 1000, 600);

    while (!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText(TextFormat("screen %i x %i", GetScreenWidth(), GetScreenHeight()), 20, 20, 20, BLACK);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

**Edit:** added the issue link and added line marks.

### CODE REVIEW

**Comment by raysan5** [comment]
@ubkp Thanks for improvement and the detailed PR!

 > Added a "temporary" SizeInt ([R359](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R359)) because it needed negative values (the -1 from GLFW_DONT_CARE) and Size had unsigned int ([R358](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R358)).

I'd prefer to avoid a new struct only for that pourpose, I think a `size = 0` in raylib side can be used for the same pourpose and just passed as `-1` to the underlying layer when required.

**Comment by ubkp** [comment]
@raysan5 Got it. I'm out of town right now, but I should be back in about 12h. As soon as I return I'll make the necessary changes. :+1:

**Comment by raysan5** [comment]
@ubkp No hurry, take it easy! 😄

**Comment by ubkp** [comment]
@raysan5 Did the following changes:

1. Removed `SizeInt`. `windowMin` and `windowMax` now use `Size` ([R398-R399](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R398-R399)).
2. Set default values to `0` instead of `-1` ([R4253-R4256](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R4253-R4256)).
3. Handled `GLFW_DONT_CARE` inside `SetWindowMinSize` ([R1795-R1799](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1795-R1799)) and inside `SetWindowMaxSize` ([R1813-R1817](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339R1813-R1817)).
4. Removed `glfwGetVideoMode` that wasn't being used for anything ([L1791](https://github.com/raysan5/raylib/pull/3309/files#diff-39fea0e3daa23741e81daf967717f35c7842426aab26a0bc3f525d6a2f03e339L1791)).

### Testing environment

Tested these new changes successfully on `PLATFORM_DESKTOP` on Linux (Mint 21.1 64-bit) and `PLATFORM_WEB` on Firefox (115.1.0esr 64-bit) and Chrome (115.0.5790.170 64-bit) both running on Linux (Mint 21.1 64-bit).

**Comment by raysan5** [comment]
@ubkp thank you very much for this nice improvement!

Just reviewing it, I'm considering renaming new variables to `screenMin` and `screenMax` for consistency with the other internal variables and considering it's already included in `Window` struct. I try to avoid as much as possible `windows` reference when variables could refer to a full display system or framebuffer size directly.

**Comment by ubkp** [comment]
@raysan5 That's an excellent idea. Actually, you told me that before on https://github.com/raysan5/raylib/pull/3206#issuecomment-1654538659, but I'm so used to think in terms of "window" that it flew past me, sorry. Just sent a PR renaming them.

**Comment by raysan5** [comment]
@ubkp thank you very much for the quick review! I was doing it myself later today... thanks!

**Pull request merged**
