### PR TITLE
fix zig syntax errors (0.11.0) in examples, and make it install executables correctly

### PR DESCRIPTION
**Pull request by purple4pur**
Related: #3386 #3393

Much appreciated @Not-Nik @star-tek-mb !

### CODE REVIEW

**Comment by raysan5** [comment]
@Not-Nik @star-tek-mb please, could you review this PR?

**Comment by star-tek-mb** [comment]
I don't know honestly.. I think we should either revert all recent changes. Either make a complex change with one top-level build.zig file. Because building from different directories - breaks everything.

I tried to build from top level and from src and from examples directory. It's hacking. I'm only using top level build.zig for package manager. And I'm not using examples and object files from src. So, we need better build design for using raylib with Zig, and using Zig toolchain to build .c files with raylib.

I can look at it, but on weekends.

**Comment by Not-Nik** [comment]
This PR only updates the example build file to Zig 0.11. We can discuss further design changes elsewhere.

**Review by Not-Nik — APPROVED** [review]

**Comment by raysan5** [comment]
@purple4pur @Not-Nik thanks for the review!

**Pull request merged**
