### PR TITLE
Add examples/shaders/shaders_lightmap.c to Makefiles

### PR DESCRIPTION
**Pull request by asdqwe**
Hello,

This pull request includes [examples/shaders/shaders_lightmap.c](https://github.com/raysan5/raylib/blob/master/examples/shaders/shaders_lightmap.c) to the Makefiles ([Makefile](https://github.com/raysan5/raylib/blob/master/examples/Makefile), [Makefile.Web](https://github.com/raysan5/raylib/blob/master/examples/Makefile.Web)), since it was missing.

Best regards.

### CODE REVIEW

**Comment by raysan5** [comment]
@asdqwe thanks for the review!

**Comment by asdqwe** [comment]
Hello @raysan5

Thanks for the reply!

Still on this subject, is there some specific reason for [core_basic_window_web.c](https://github.com/raysan5/raylib/blob/master/examples/core/core_basic_window_web.c) not being included on the Makefiles? I only saw mentions of it: [Makefile#L325-L328](https://github.com/raysan5/raylib/blob/master/examples/Makefile#L325-L328), [Makefile.Web#L295-L298](https://github.com/raysan5/raylib/blob/master/examples/Makefile.Web#L295-L298).

If not, I can send a pull request to add it.

Best regards.

**Comment by raysan5** [comment]
@asdqwe I just prefer not to include it, it's just a sample of `core_basic_window.c` reformatted for emscripten... but actually nowadays it is not really needed, `ASYNCIFY` works really good with regular C code structure.

**Comment by asdqwe** [comment]
Hello @raysan5 

Got it! Thanks for the explanation!

Best regards.

**Pull request merged**
