### PR TITLE
new models_magicavoxel_loading example

### PR DESCRIPTION
**Pull request by procfxgen**
I created a new example to load magicavoxel file format.
https://ephtracy.github.io/

I added the example for the visual studio only.

Makefile must be updated for linux ...

### CODE REVIEW

**Comment by raysan5** [comment]
@procfxgen This is a quite long example, would it be possible to move the Magiavoxel VOX loader to a separate portable header-only file?

**Comment by procfxgen** [comment]
Yes, I'll change my code :-)

**Comment by raysan5** [comment]
@procfxgen If VOX is ported to portable header-only, I think we can move the VOX loader into raylib `models` module. I can help with that.

**Comment by procfxgen** [comment]
It's done.

**Comment by procfxgen** [comment]
I fixed magicavoxel loader example, It's working under raspberry pi now.

**Comment by procfxgen** [comment]
@raysan5 It's fine for you ?

**Comment by raysan5** [comment]
@procfxgen The loader requires some redesign, at this moment it depends on raylib and raymath types and that's not desired. All the file-format loaders in raylib are self-contained and header-only, they define their own data types that are copied to raylib types on loading. The loader should also support loading from memory, not only loading from file. 

Also, the included models LICENSE must be included, are they free to use? it desirable for resources to be CC0?

**Comment by procfxgen** [comment]
I'll put my loader without raylib dependencies into "src/external"
@raysan5 But where I put my code in order to convert my own data types to raylib types ? into my example ?

**Comment by raysan5** [comment]
@procfxgen It should be inside raylib `models` module, in a `LoadVOX()` function, called by `LoadModel()`, similar to `LoadOBJ()` and `LoadIQM()`.

**Comment by procfxgen** [comment]
@raysan5  It's done, tell me what you think about it :-)

**Comment by raysan5** [comment]
@procfxgen Wow! You did a great work! Thank you very much! I'm merging it! :D

**Comment by procfxgen** [comment]
@raysan5  Thank you for RayLib :-)

**Pull request merged**
