### PR TITLE
Bump version to 1.9.4

### PR DESCRIPTION
**Pull request by a3f**

### CODE REVIEW

**Comment by raysan5** [comment]
Ouch! I miss that! Should I launch a new release? I can cancel previous one...

**Comment by a3f** [comment]
I think that would be the best, to avoid confusion as this release has the version embedded in the libraries and the pkg-config files. I am in favor of a 1.9.4-dev (To avoid breaking people who have pulled 1.9.3-dev already…)

**Comment by raysan5** [comment]
> Should I push a 1.9.4?

Sure. I'm also changing it in raylib internals and integrating to master again.

**Comment by raysan5** [comment]
Just as a note, we should find a way to automatically pick version from somewhere instead of changing version number text manually inside raylib.

**Comment by a3f** [comment]
Suggestion: Check if git is available and use `git describe --tags`. This returns `1.9.3-dev` on `master`. If there are commits since the tag, it appends a commit id after the tag. Pass it as `RAYLIB_VERSION` macro to build process. If there's no git, we'll need to use a hardcoded value as fallback.

**Pull request merged**
