### PR TITLE
CMake: Remove USE_WAYLAND option

### PR DESCRIPTION
**Pull request by M374LX**
With GLFW now having both X11 and Wayland enabled by default, the ``USE_WAYLAND`` CMake option is no longer necessary.

Setting GLFW's own CMake options ``GLFW_BUILD_X11`` and ``GLFW_BUILD_WAYLAND`` to ``OFF`` allows either to be disabled.

This PR additionally includes a check to prevent both from being disabled.

### CODE REVIEW

**Comment by raysan5** [comment]
@M374LX Thanks for the review! It seems this change is generating some issues in the CI build system...

**Comment by M374LX** [comment]
@raysan5 The CI fails with the message:
`` Failed to find wayland-scanner``

This means that the ``wayland-scanner`` utility is missing in the machine that runs the build test, but installing it should fix the problem. On Debian, for instance, the package to be installed is ``libwayland-bin``.

**Comment by Peter0x44** [comment]
https://github.com/raysan5/raylib/blob/25caf14be8d0284aceaa0de28753b3012e71b7bb/.github/workflows/cmake.yml#L89

Adding libwayland-bin here would be the solution, I guess.

But now I'm questioning - doesn't the Makefile need this too?

**Comment by raysan5** [comment]
@M374LX Added `libwayland-bin` to CI system for linux builds.

@Peter0x44 Afair, Makefile does not manage those deps, are expected to be installed in the system by user.

**Comment by Peter0x44** [comment]
@raysan5 I was talking about the ci system for the makefile

**Comment by raysan5** [comment]
@Peter0x44 Oh, ok, I think I already modified it. Just reviewed CMake build CI.

**Comment by M374LX** [comment]
@Peter0x44 There is a deeper issue affecting the Makefile and the Zig build system (#3850), which I plan to review too.

**Pull request merged**
