### PR TITLE
Added "New" and "NewV" functions

### PR DESCRIPTION
**Pull request by NuklearBomb**
`New` and `NewV` functions have been added for creating `Vector2`, `Vector3`, `Quaternion`, and `Matrix`.

```
// Old way
Vector2 foo={0, 1}, bar={5, 3}, res;
res=Vector2Add(foo, bar);
```
```
// New way
Vector2 res;
res=Vector2Add(Vector2New(0,1), Vector2New(5,3));
```
This example is a bit simple, and more complex code would benefit the most from this update. This will definitely make it easier to write and maintain streamlined code.

### CODE REVIEW

**Comment by a3f** [comment]
What's wrong with
```
// C99 way
Vector2 res;
res=Vector2Add((Vector2){0,1}, (Vector2){5,3});
```

**Comment by TheLumaio** [comment]
I was in the process of asking exactly that.
It's less code and you don't get the function call overhead

**Comment by TheLumaio** [comment]
Also, isn't `Vector2 Vector2NewV(float arr[2])` invalid in C99?

**Comment by NuklearBomb** [comment]
Wow, why didn't I think of that? Very cool, and way better! @a3f

**Pull request closed without merging**
