### PR TITLE
Fixed some games. Replaced font.size with font.baseSize. Uncommented linux libs.

### PR DESCRIPTION
**Pull request by RDR8**
Maybe these are exercises for your students?

### CODE REVIEW

**Comment by raysan5** [comment]
Wow! Amazing work @RDR8! It was on my TODO list reviewing all those games to latest raylib version!

Thank you very much for the effort! :D

**Comment by RDR8** [comment]
You're welcome! The monsters in Skully are frighteningly​ fun. Great sound effects. Wave Collector crashes after pressing enter at the loading screen.  Going through /examples next. 😀 After I get a handle on make, will learn gdb.

**Comment by raysan5** [comment]
Thanks again @RDR8! About Wave Collector, I'm aware of the crash, it happens randomly, I haven't touched raylib_demo since version 1.0 or so... yeah, templates folder also requires some review...

**Comment by RDR8** [comment]
Nothing to report in /templates. (^:

**Pull request merged**
