### PR TITLE
Gamepad Rework

### PR DESCRIPTION
**Pull request by Rover656**
This reworks gamepads so that all button and axis mappings go through the same enum, instead of controller specific controls.

Desktop and UWP Gamepads have been tested and work correctly. Desktop (on windows, if GLFW mapping works here, it should work everywhere else) has been tested with an XB1 and PS4 controller, and UWP just with the XB1.

Web has not been tested as I am unable to test, but what I have written comes straight from the w3 docs and so should be correctly mapping buttons and axis to the new enum's aswell.

### CODE REVIEW

**Comment by Rover656** [comment]
Just noticed all the examples need updating... I shall get on that.

**Comment by raysan5** [comment]
Ok, just answered two of my three questions (TABS, gamepad examples).

Third question: What about Android gamepad? I just been investigating it right now and it seems gamepad inputs on Android come in the form of key inputs... not sure how to deal with that properly... neither have an Android gamepad for testing... probably we can skip that part for now.

**Comment by Rover656** [comment]
I have ignored Android gamepads for now as I did not find them implemented and I am unsure as to how to add Android support to it.

**Comment by raysan5** [comment]
ok, do you want me to wait for the examples review before merging?

**Comment by Rover656** [comment]
Yeah please, I am just in the middle of updating the gamepad example to the correct enums, but nothing more. My aim is for it to build and the example to work, not worrying about controller identification for the moment.

**Comment by Rover656** [comment]
That should be it sorted, I'm going to wait for the build to complete before giving the go-ahead.

**Comment by raysan5** [comment]
take it easy, no hurries... :)

**Comment by raysan5** [comment]
It seems there is some issue on `PLATFORM_WEB`:
```
/src/src/core.c:3488:57: error: use of undeclared identifier 'k'
                const GamepadAxis axis = GetGamepadAxis(k);
```

**Comment by Rover656** [comment]
Oh, I see, 2 seconds

**Comment by Rover656** [comment]
That should fix it

**Comment by raysan5** [comment]
@Rover656 Thnak you very much for another great contribution! :)

**Pull request merged**
