### PR TITLE
Added fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer to integrate Raylib into OSS-fuzz.
Fuzzing is a method of testing applications where pseudo-random data is passed into a target - in this case `LoadFont `- with the goal of finding bugs and vulnerabilities.

In this fuzzer, a file is created with the pseudo-random data and the file is loaded by LoadFont. The fuzzer is implemented by way of LibFuzzer which is a coverage-guided fuzzing engine. This means that as the fuzzer generates new coverage, it uses the feedback from this for future input-data creation. 

I have worked on the integration to setup continuous fuzzing of Raylib with OSS-fuzz which is a project by Google where open source projects can have their fuzzers run continuously free of charge - With an implied expectation that bugs are fixed. If bugs are found, maintainers get sent a link to a detailed bug report.
OSS-fuzz has a public disclosure policy of 90 days.
I will be happy to finalize the integration into OSS-fuzz. All that is needed are the email addresses of maintainers to receive potential bug reports. These can be shared here, via email to me or in the integration application on the OSS-fuzz side.

### CODE REVIEW

**Comment by raysan5** [comment]
@AdamKorcz Thanks for PR but, for the moment, there are no plans to integrate a fuzzer on raylib. You can integrate it in your fork and open an issue with the potential bug reports for review.

**Comment by AdamKorcz** [comment]
@raysan5 Thank you for the quick reply. May I ask if there is interest in fuzzing Raylib without integrating fuzzers into the Raylib repo? We can easily host the fuzzers the fuzzers on the OSS-fuzz repository.

**Comment by raysan5** [comment]
What does it imply for raylib and for me as maintainer?

**Comment by AdamKorcz** [comment]
The following things are the broad implications:

- You will get email notifications of bugs and build failures. The build failures will happen when changes happen in either Raylib, OSS-fuzz and/or dependencies. 
- Founds bugs by the fuzzers with be publicly disclosed after 90 days.
- It will be public that Raylib is being fuzzed by OSS-fuzz, however fuzz data is only available for maintainers on the mailing list.
- To see bug reports you will have to sign the Google CLA.

**Comment by raysan5** [comment]
@AdamKorcz Thanks for the detailed explanation. I'm afraid I'm not interested at this moment

**Comment by AdamKorcz** [comment]
No problem! Feel free to reach out in case fuzzing is added to the roadmap of Raylib.

**Pull request closed without merging**
