### PR TITLE
Update compilation warning flags

### PR DESCRIPTION
**Pull request by danimartin82**
Hi all. My first PR here!!

I have been reviewing many compilation flags for warnings  and testing them (the complete list is 
`gcc --help=warning`). So far I tested the next ones:

```
-Wbad-function-cast -Wbool-compare  -Wbool-operation -Wbuiltin-declaration-mismatch -Wcast-align -Wcast-qual -Wchar-subscripts -Wcharacter-truncation -Wchkp -Wconversion-extra  -Wdeprecated -Wformat-overflow -Wfree-nonheap-object -Wimplicit -Wint-in-bool-context -Wint-to-pointer-cast -Winteger-division -Wmissing-parameter-type -Wmissing-prototypes -Woverlength-strings -Wpointer-sign -Wpointer-to-int-cast -Wunused
-Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-const-variable -Wunused-const-variable -Wunused-dummy-argument -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-macros -Wunused-parameter -Wunused-result -Wunused-value -Wunused-variable
```

And being honest....I didn't see any of them adding useful info for improving the code. Indeed I ended up with the oposite proposal: 

With the `-Wall` flag many warnings shown always (`-Wunused-function` and similars). They report that functions are not being used in textures.c and in many files in external folder. As these files are  complete libraries and not all of their functions are being used, this warnings are OK and they can  be ignored always. 

So my proposal here is:
* If the warnings have to be ignored...then the warnings are not useful. That's why I removed them.
* To continue the work in static analysis of raylib in order to detect dead code and any other potential risk.

any comment is welcome!!

### CODE REVIEW

**Comment by raysan5** [comment]
Hi @danimartin82, nice review!

You removed `-std=c99`, I think we need this one, raylib uses C99.

**Comment by danimartin82** [comment]
> Hi @danimartin82, nice review!
> 
> You removed `-std=c99`, I think we need this one, raylib uses C99.

aaargh!!! sorrry!! An error with copy/paste..... fixed

**Comment by raysan5** [comment]
@danimartin82 nice! merging! :)

**Comment by raysan5** [comment]
@danimartin82 I'm afraid I have to revert this commit because when compiling for web (`clang`) most of the warning options are not recognized while `-Wall` setup the supported ones by the compiler.
```
warning: unknown warning option '-Wbool-compare' [-Wunknown-warning-option]
warning: unknown warning option '-Wbuiltin-declaration-mismatch'; did you mean '-Wmissing-declarations'? [-Wunknown-warning-option]
warning: unknown warning option '-Wchkp'; did you mean '-Wcpp'? [-Wunknown-warning-option]
warning: unknown warning option '-Wformat-overflow'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wfree-nonheap-object'; did you mean '-Wsequence-point'? [-Wunknown-warning-option]
warning: unknown warning option '-Wmissing-parameter-type' [-Wunknown-warning-option]
```
Reverted in commit https://github.com/raysan5/raylib/commit/66e0d774bdd4a084c4180c8ffc5d4e0dcef27861.

**Comment by danimartin82** [comment]
ok, understood

**Pull request merged**
