### PR TITLE
[rcore] Fix #4405

### LINKED ISSUE #4405: [Gamepad] Remove default gamepad axis deadzone on MacOS/GLFW
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Issue description

> Edit: The following sentence isn't relevant as it was misdiagnosed: Raylib expects a [compile time constant to set the deadzone](https://github.com/raysan5/raylib/blob/110ee74875412beb41ffb53330b47ec9cb052b2d/src/external/RGFW.h#L5665)

Raylib does not appear to have an API to set the deadzone of a controller, yet it exists and is defaulted on the GLFW backend on MacOS.

This should be up to the user in game as
1. Gamepads with [HALL-effect sensors](https://www.youtube.com/watch?v=oAsrLxaAkY0) may have zero drift, and users will be hamstrung by arbitrary drift. This may be needed for FPSs and simulator games requiring precision control.
2. Users with older potentiometer controllers may have larger drift amounts that need to be manually set.

In order to accommodate this an API is required for setting the dead-zone independently for each controller axis, of each gamepad.

In addition hard coding this requires recompilation of the library if used by JS, Python or other scripting wrapper (I'm using [Vybe](https://github.com/pfeodrippe/vybe)), preventing the wrapper from hosting "it just works out the box" compiled version of Raylib in their library. 

Solutions in ascending order of difficulty:
1. A stepping stone solution would simply be to default it 0.0 which would allow all games to handle this in game code. Solves for wrappers.
2. An API that allows settings a single setting across all controller axis in game.
3. An API that allows setting for each hardware axis independently for each controller (this properly models reality of user's controllers).

No expectations, just posting to start a discussion. Thanks for the library :-)

### Environment

Platform backend: DESKTOP (GLFW) on MacOS

### Issue Screenshot

N/A

### Code Example

In issue description.

### PR DESCRIPTION
**Pull request by asdqwe**
All credits to @dmg46664 for finding this issue (#4405, [ref](https://github.com/raysan5/raylib/issues/4405#issuecomment-2429195055)) and pointing the solution. Great catch!

Summary: At the moment a mininum value of `0.1f` is being applied on all gamepad axis at all times on all platforms. Since the deadzone depends on each specific gamepad, it's indeed something that should be exposed to the end-user (e.g.: the player playing the game) be able to adjust to his case at runtime. This PR adds deadzone to `CORE.Input.Gamepad` and exposes `SetGamepadDeadzone()` to set that value. It also allows the dev-user to zero it and handle the deadzone himself.

<details>
<summary>This PR can be tested with:</summary>

```
#include "raylib.h"
int main(void) {
    InitWindow(400, 300, "test");
    SetTargetFPS(60);

    // Control the deadzone here:
    SetGamepadDeadzone(0.001f);

    while (!WindowShouldClose()) {

        // Get axis values:
        float lax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X);
        float lay = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_Y);
        float rax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_X);
        float ray = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_Y);

        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawCircle(100, 80, 50, LIGHTGRAY);
        DrawCircle(100+(int)(lax*50), 80+(int)(lay*50), 5, RED);
        DrawText(TextFormat("LAX %f", lax), 30, 140, 20, BLACK);
        DrawText(TextFormat("LAY %f", lay), 30, 160, 20, BLACK);

        DrawCircle(300, 80, 50, LIGHTGRAY);
        DrawCircle(300+(int)(rax*50), 80+(int)(ray*50), 5, BLUE);
        DrawText(TextFormat("RAX %f", rax), 230, 140, 20, BLACK);
        DrawText(TextFormat("RAY %f", ray), 230, 160, 20, BLACK);

        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```
</details>

<details>
<summary>And devs can implement individual deadzones like this:</summary>

```
#include "raylib.h"
int main(void) {
    InitWindow(400, 300, "test");
    SetTargetFPS(60);

    // Set axis deadzones:
    SetGamepadDeadzone(0.0f);
    int dz = 0;
    float laxdz = 0.5f;
    float laydz = 0.5f;
    float raxdz = 0.5f;
    float raydz = 0.5f;

    while (!WindowShouldClose()) {

        // Toggle deadzone: [gamepad button A]
        if (IsGamepadButtonPressed(0, GAMEPAD_BUTTON_RIGHT_FACE_DOWN)) { dz = !dz; }

        // Get axis values:
        float lax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_X);
        float lay = GetGamepadAxisMovement(0, GAMEPAD_AXIS_LEFT_Y);
        float rax = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_X);
        float ray = GetGamepadAxisMovement(0, GAMEPAD_AXIS_RIGHT_Y);

        // Calculate deadzones:
        if (dz) {
            if (lax > -laxdz && lax < laxdz) { lax = 0.0f; }
            if (lay > -laydz && lay < laydz) { lay = 0.0f; }
            if (rax > -raxdz && rax < raxdz) { rax = 0.0f; }
            if (ray > -raydz && ray < raydz) { ray = 0.0f; }
        }

        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawCircle(100, 80, 50, LIGHTGRAY);
        if (dz) { DrawEllipse(100, 80, 50*laxdz, 50*laydz, BLACK); }
        DrawCircle(100+(int)(lax*50), 80+(int)(lay*50), 5, RED);
        DrawText(TextFormat("LAX %f", lax), 30, 140, 20, BLACK);
        DrawText(TextFormat("LAY %f", lay), 30, 160, 20, BLACK);

        DrawCircle(300, 80, 50, LIGHTGRAY);
        if (dz) { DrawEllipse(300, 80, 50*raxdz, 50*raydz, BLACK); }
        DrawCircle(300+(int)(rax*50), 80+(int)(ray*50), 5, BLUE);
        DrawText(TextFormat("RAX %f", rax), 230, 140, 20, BLACK);
        DrawText(TextFormat("RAY %f", ray), 230, 160, 20, BLACK);

        DrawText("Toggle deadzone:\n[gamepad button A]", 30, 220, 20, BLACK);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```
</details>

Fixes #4405.

### CODE REVIEW

**Comment by raysan5** [comment]
@asdqwe Is it really required to add a new function to raylib API? I'd prefer to avoid that if it could be managed on user side.

**Comment by asdqwe** [comment]
@raysan5 Unfortunately, at the moment, the `0.1f` minimal deadzone value is hardcoded on the `GetGamepadAxisMovement()` ([here](https://github.com/raysan5/raylib/blob/ebcfc7f49e925f0ff5ddfa744e44bdc1c50ed2a2/src/rcore.c#L3299)). While the user can **increase** that value on the client-side by adding additional deadzone, the user **can't reduce** it or zero it except by editting `rcore.c` directly.

An alternative would be using a `#define` [like this branch](https://github.com/raysan5/raylib/compare/master...asdqwe:raylib-fork:fix-gamepad-deadzone-static). However, that's a fixed compile-time value and deadzones need to be adjusted on a controller-by-controller basis. In this case, the best the dev could do is to zero that `#define`, but that excludes anyone using raylib from repositories.

To make that accessible on runtime, I don't know another way. Can the user change `CORE.Input.Gamepad.*` values directly? That didn't work when I tried on the test case.

**Comment by asdqwe** [comment]
@raysan5 Removed the deadzone as per https://github.com/raysan5/raylib/issues/4405#issuecomment-2430432197.

**Comment by raysan5** [comment]
@asdqwe thanks for the review!

**Comment by asdqwe** [comment]
@raysan5 Do you want me to add deadzone handling to the `core_input_gamepad.c` so new users have a reference on how to implement it themselves?

**Comment by raysan5** [comment]
@asdqwe that would be great! thanks! 👍🙂

**Pull request merged**
