### PR TITLE
[rlgl] Reviewed `rlUpdateShaderBuffer()`, it can not update the size

### PR DESCRIPTION
**Pull request by MrScautHD**
With this change `rlUpdateShaderBuffer` updates the size of the buffer.

### CODE REVIEW

**Comment by raysan5** [comment]
@MrScautHD I'm afraid I don't understand this PR, it looks confusing to me on its intended behaviour... It should be reviewed more carefully...

**Comment by MrScautHD** [comment]
> @MrScautHD I'm afraid I don't understand this PR, it looks confusing to me on its intended behaviour... It should be reviewed more carefully...

After you set the size in loadbuffer you can not anymore change the size in the buffer update

**Comment by raysan5** [comment]
> After you set the size in loadbuffer you can not anymore change the size in the buffer update

And that's the expected behaviour, `rlUpdateShaderBuffer` is sued to **update** an existent pre-defined shader buffer, not change its size.

**Comment by MrScautHD** [comment]
:/

**Pull request closed without merging**
