### PR TITLE
[games_linux_make_fix] Fix building the games on Linux by adding missing libs

### PR DESCRIPTION
**Pull request by xspager**

### CODE REVIEW

**Comment by raysan5** [comment]
Hi @xspager! Just checking this pull-request right now and saw your change! Actually, you did the pull-request again to my master branch instead of develop, you are trying to merge your branch into `master` instead of `develop`. You can see that info at the top of the PR.

Don't worry about it, I'll just wait for the final integration from my `develop` branch into `master` and then I'll integrate your changes.

Thanks again for your effort and for your time! :)

**Comment by xspager** [comment]
Oh, sorry. I misunderstood what you meant, should've been obvious. Do you
like me to try to create the right PR?

Sorry for my confusion :/

**Comment by raysan5** [comment]
As you want, if you want to try again it's ok. If not I can integrate it later. Any option is right for me. :)

**Comment by xspager** [comment]
I think the other one is ok

**Pull request closed without merging**
