### PR TITLE
[rnet] module WIP

### PR DESCRIPTION
**Pull request by Syphonx**
I've been very busy with life the last few months & i don't think i'll be able to continue working on rnet in the capacity that i would like to, i'd rather submit a WIP PR so that this work doesn't go to waste as i've seen quite a few people asking about it on discord

This pull request serves as a full handover - I'll happily make small requested changes (formatting, style, small api additions and bug fixes) to the code going forwards but i won't be able to dedicate much (if any) additional time to the project.

[rnet] is still very much a WIP, so there _will_ be sections not working, sections entirely un-commented and stuff that i wrote in a caffeinated haze, i hope this code is useful to some :D

Note:
A few functional examples are available that demonstrate how to setup a basic UDP or TCP Client/Server, these can be found in /examples/network

### CODE REVIEW

**Comment by raysan5** [comment]
@Syphonx Sorry, it's a bit difficult for me to review all this commit, there are several files that shouldn't be modified (Visual Studio projects, `core_basic_window`, raylib.h...) and all changes should be provided as a single commit...

Do you mind if I discard this PR and add rnet module and examples just manually copying them from your repo?

**Comment by victorfisac** [comment]
> @Syphonx Sorry, it's a bit difficult for me to review all this commit, there are several files that shouldn't be modified (Visual Studio projects, `core_basic_window`, raylib.h...) and all changes should be provided as a single commit...
> 
> Do you mind if I discard this PR and add rnet module and examples just manually copying them from your repo?

Just a note about commits, if this PR is valid you can merge all comits into one using the option "Merge and Squash". This option will ask you what is the final commit message like a summary to appear in commits list of master branch.

**Comment by raysan5** [comment]
Hey @victorfisac! Thanks for the info! :D

**Comment by Syphonx** [comment]
Apologies for the extra file changes (i didn't catch those), i've updated the latest commit with the suggestions!

I'm not quite sure how to merge/squish the PR, but once we're happy with the final commit i'll look into squishing it :)

**Pull request merged**
