### PR TITLE
glfw: Sync our GLFW with upstream master

### PR DESCRIPTION
**Pull request by a3f**
glfw/glfw@5595fa3 implements a proper fix for the macOS Mojave
problem of OpenGL windows not being rendered until moved or manually
updated.

Pull in the current master and rebase the two commits we have for reuse
of the GLFW CMake build system for Wayland on top. It hasn't been merged
(or acknowledged..) upstream yet.

Fixes #655 and #665.

### CODE REVIEW

**Comment by a3f** [comment]
Will fix the Windows build error later

**Comment by raysan5** [comment]
Just note that `src/external/glfw/include/GLFW/glfw3native.h` was modified by me for raylib to avoid conflicting symbols with `windows.h`.

**Comment by raysan5** [comment]
@a3f any news on this PR?

**Comment by a3f** [comment]
I've fixed the Windows build error, but Travis still fails because of the `RL_RG` commit.

**Comment by raysan5** [comment]
@a3f Thanks for reporting, it should be ok in commit https://github.com/raysan5/raylib/commit/f4fe7f4d4c6d25e4bcc1ea4b48af07ef49b82720.

By the way, could you take a look to https://github.com/raysan5/raylib/issues/681, tried to test Windows support for Travis CI but it keeps failing...

**Pull request merged**
