### PR TITLE
Add uConsole mapping

### PR DESCRIPTION
**Pull request by carverdamien**

### CODE REVIEW

**Comment by raysan5** [comment]
@carverdamien Great addition! Did you try raylib on uConsole? How did it work? Did it require some tweaks? I got the uConsole but I haven't tried it yet...

**Comment by carverdamien** [comment]
Thanks @raysan5!

I have the RPi-CM4 version and I'm using zig to write my games. Regarding tweaks, we already merged this change 3 months ago https://github.com/raysan5/raylib/pull/4049

So far, I've used a very narrow range of features from raylib. Mainly stuff from the 2d_camera example.

I've been focusing on my custom network code. I'm doing everything on the uConsole. My next step is to cross compile for Windows and see if two players can play together: one on the uConsole and the other on Windows.

I'll keep sending PR if I see any issue with raylib.

**Comment by Peter0x44** [comment]
Shouldn't this be submitted upstream to glfw?

**Comment by carverdamien** [comment]
> Shouldn't this be submitted upstream to glfw?

Yes. Can someone do it and post a link here?

**Comment by sleeptightAnsiC** [comment]
> > Shouldn't this be submitted upstream to glfw?
> 
> Yes. Can someone do it and post a link here?

This mapping is already in [SDL_GameControllerDB](https://github.com/mdqinc/SDL_GameControllerDB/blob/bf3617aec3f1d7c9cefdf6dba691928b8846b9f7/gamecontrollerdb.txt#L1281). It should propagate to GLFW when they update their mappings, so no worries.

**Pull request merged**
