### PR TITLE
Fix ImageTextEx and ImageDrawTextEx scaling

### PR DESCRIPTION
**Pull request by hatkidchan**
Already explained in #2755, should close it.

Also it would be nice to specify a scaling method 'cause not all fonts look great when using cubic interpolation, but that can be easily done manually by drawing text with "native" font size first and then using `ImageResizeNN` if desired

### CODE REVIEW

**Comment by hatkidchan** [comment]
oh wow, I probably should've created another fork for that or just didn't sync it with upstream

that looks scary
image

hopefully it's not big of a deal

**Comment by raysan5** [comment]
@hatkidchan Hey! Thanks for the detailed issue review and the fix provided! :D

**Comment by hatkidchan** [comment]
no problem!

sometimes it feels like raylib lacks some deep testing of obscure features like that though-
glad to be able to help with at least some of them

**Comment by raysan5** [comment]
@hatkidchan You are right, raylib lacks some deep testing of features but I'm developing alone and I can't do everything in the way I'd like to, sometimes new features are not properly tested or just tested on Windows platform... Hopefully community can help with that...

**Pull request merged**
