### PR TITLE
Add methods to transform the VR output

### PR DESCRIPTION
**Pull request by shraiwi**
# This PR:
- Adds a function to the VR simulator called `SetVrOutputTransform()` that allows users to rotate and reflect the VR simulator output
- Adds logic in `EndVrDrawing()` that will transform the VR output according to the transform flags
- Adds `VrOutputTransform` enum
- Updates the `core_vr_simulator` example to include `SetVrOutputTransform()`

# For example:
`VR_OUTPUT_ROTATE_NONE`
VR_OUTPUT_ROTATE_NONE

`VR_OUTPUT_ROTATE_180`
Screenshot from 2021-02-10 10-20-38

`VR_OUTPUT_FLIP_V | VR_OUTPUT_ROTATE_180`
VR_OUTPUT_FLIP_V | VR_OUTPUT_ROTATE_180

# Why?
To my knowledge, raylib is the only library that has a VR simulator that can be used to directly drive a real VR headset. However, not all VR headset displays are mounted vertically. By adding this functionality, it would be easy for users using phones or embedded systems (such as the Pi 4) to rotate and/or flip the display without a window server. Since the transformations just change vertex coordinates, it has a negligible performance impact.

### CODE REVIEW

**Comment by raysan5** [comment]
@shraiwi Thanks for the review and excuse me for my late response. I'm still thinking about merging those changes or not, I'm considering instead adding an option to get the framebuffer and let the user manage it as desired.

**Comment by shraiwi** [comment]
That might be a better idea, because then they could use the framebuffer for other things as well.

**Comment by shraiwi** [comment]
Should I close this PR?

**Comment by raysan5** [comment]
@shraiwi not yet, I prefer to keep it open for me to remember.

**Comment by raysan5** [comment]
@shraiwi VR simulator has been moved to core module and completely redesigned. Now user is in charge of stereo-render fbo and also in full control of distortion shader. Example code is a bit more complex but better aligned with other raylib examples.

**Pull request closed without merging**
