### PR TITLE
Changed minimum vertices for circle shapes from 4 to 3 to allow drawing of triangles

### PR DESCRIPTION
**Pull request by MikeDX**
This PR reduces the minimum vertices of circles from 4 (square) to 3 (triangle) to allow drawing of triangle primitives (filled and outline)

### CODE REVIEW

**Comment by raysan5** [comment]
@MikeDX I'm not implementing this change, actually triangles can be already drawn with `DrawCircle()`. This function is specific for sector drawing, not intended for triangles.

**Comment by MikeDX** [comment]
That is a real shame, since it is really useful and costs nothing to implement and is useful 
Screenshot 2020-01-02 at 09 52 07 for instance for this

**Comment by raysan5** [comment]
@MikeDX Why not using `DrawCircle()` to do the same?

**Comment by MikeDX** [comment]
I don't believe drawcircle will do just outlines nor will it do circles of varying certices

If I'm wrong though, I'm happy to use that!

Otherwise my project will have to use a forked raylib :(

**Comment by raysan5** [comment]
@MikeDX ok, I see. What about `DrawRing()`, `DrawRingLines()` or `DrawPoly()`?

**Comment by MikeDX** [comment]
My current implementation is this:

```c
int F_circle(int x, int y, float radius, int points, Flua_Colour col, int outline) {
	Vector2 center = {x, y};
	
	if(outline) {
		DrawCircleSectorLines(center, radius, 0, 360, points, col);      // Draw a piece of a circle
	} else {
		DrawCircleSector(center, radius, 0, 360, points, col);      // Draw a circle sector outline
	}

	return 0;
}
```

Does Draw* give me the same ability in the same simple way?

**Comment by raysan5** [comment]
@MikeDX I think `DrawPoly()` let you draw that kind of shapes, actually it's intended for that. `DrawCircleSector()` was intended for other kind of shapes.

**Comment by MikeDX** [comment]
DrawPoly works great for a filled shape but drawRing falls back to circle at 3 points

**Comment by raysan5** [comment]
Ok, so a `DrawPolyLines()` is required.

I checked `DrawRing()` and it uses `DrawCircleSector()` internally.

`DrawRing()` and `DrawCircleSector()` were added by a raylib user, I will review them again.

**Comment by MikeDX** [comment]
If you can add a DrawPolyLines, that will make me happy

I still think reducing the minimum sectors is a zero cost addition, since 3 is no less valid than 4

**Pull request closed without merging**
