### PR TITLE
Bump version no. in CMake build file

### PR DESCRIPTION
**Pull request by define-private-public**
I saw that you added a new release, but didn't bump the version no. here.

### CODE REVIEW

**Comment by raysan5** [comment]
Hi @define-private-public, could you send PR to develop branch? I keep latest released stable version in master branch, that's 1.8.

**Comment by define-private-public** [comment]
I could do that if you wanted to, but I intended this to be a fixup for the latest released stable version branch.  I can move that over to `develop` if you'd like, but here's my argument for why it needs to go into `master`:

Say if someone clones `master` and then does the CMake build & install steps.  While the code in `master` is at v1.9.1, The built/installed CMake files will report that raylib is at 1.8.

**Comment by raysan5** [comment]
The code in `master` is at 1.8. No changes integrated since that release.

**Comment by define-private-public** [comment]
Oh, it is?  I was a little confused by this on the Releases page: 
https://github.com/raysan5/raylib/releases/tag/1.9.1-dev

I'll go and adjust the PR now.

**Comment by define-private-public** [comment]
Looking at the conflict now, then my PR might be moot now.  I'll let you decided what to do.

**Comment by raysan5** [comment]
Hi @define-private-public, 

Latest available release is generated from develop branch and it was an automatization test, binaries are generated by the continuous integration system and automatically attached to the release, @a3f implemented that system. 

For now I'll discard this PR but many thanks for your effort.

**Pull request closed without merging**
