### PR TITLE
Add example shaders_shapes_outline

### PR DESCRIPTION
**Pull request by GoldenThumbs**

### CODE REVIEW

**Comment by raysan5** [comment]
@GoldenThumbs thank you very much! This exampke is a nice addition! 👍

**Comment by jamesl-github** [comment]
what does it mean when an example is copyrighted by the submitter ?

**Comment by raysan5** [comment]
@jamesl-github that the submitter is the original creator of the example.

**Comment by jamesl-github** [comment]
> that the submitter is the original creator of the example.

what I meant was how does that affect licensing            
are all examples released under the same license as raylib ? 
is it explicitly stated somewhere that any example you submit to raylib automatically acquires and falls under the raylib license ?
most licenses I see say "attribution required" or "attribution appreciated, but not required"  
they also say things like "can be used in both commercial and non-commercial code with or without modification" 
so I was wondering if the submitter retains all rights to the code or if the code acquires raylib's license

**Comment by raysan5** [comment]
@jamesl-github Afaik, all contributed examples fall under the same license as raylib: zlib/libpng if nothing different is specified

**Pull request merged**
