### PR TITLE
fixed free camera pitch rotation

### PR DESCRIPTION
**Pull request by chriscamacho**
pitch rotation was only being done on one axis
this allows you to look straight up and down, other camera modes will need this method implementing...

### CODE REVIEW

**Comment by raysan5** [comment]
Hi @chriscamacho not sure if I understand the issue... please, could you provide an example? or can I check the issue in some of the existing examples?

**Comment by chriscamacho** [comment]
On Sun, 29 Dec 2019 03:23:14 -0800
Ray <notifications@github.com> wrote:

> Hi @chriscamacho not sure if I understand the issue... please, could
> you provide an example? or can I check the issue in some of the
> existing examples?
> 

in order to rotate through one axis your calculation must effect the
other two axes.

an X axis rotation effects Y & Z for example

Your 2 axis rotations are only effecting 3 axes not 4 

Z heading should effect X & Y 
Y pitch should effect X(again) and Z

You can see the current calculation is incorrect if you take off the
pitch limit, instead of the pitch going around a full 360 it pitches up
and down in a sine wave like motion, this means you can only look down
45 degrees (not straight down or even 5 degrees off).  You need to
either add an additional calculation OR just pick the result out of a
matrix like the PR shows you.

**Comment by raysan5** [comment]
@chriscamacho ok, I understand, previous implementation limited the pitch when looking around, probably related to the Euler math. Merging.

**Comment by chriscamacho** [comment]
please note I only had chance to implement it on one mode, you'll need to review the other places with the same issue....

**Pull request merged**
