### PR TITLE
build.zig: Improve logic

### PR DESCRIPTION
**Pull request by sagehane**
Currently, the project was failing to build when trying `zig build` inside the `src/` dir instead of the root dir, due to hardcoding the path *from* the relative dir to `"src"`, such that the compiler will try to look for `$PROJECT_ROOT/src/src/<path>` instead of `$PROJECT_ROOT/src/<path>`. I tried to fix all such instances of `"src"` with the parent directory of `@src().file`.

Also, exposed the `Options` type so people can do more things with it.

### CODE REVIEW

**Comment by raysan5** [comment]
@sagehane Thank you very much for the review!

**Comment by Not-Nik** [comment]
This breaks the build for me on Zig 0.13, because the path is no longer relative. Platform is macOS 14.6.1

**Comment by raysan5** [comment]
@sagehane please, could you review @Not-Nik issue?

**Comment by sagehane** [comment]
Yes, I'll try. I'm sorry, seems this breaks for 0.12.0 too (which is the advertised supported version). There were other confusing aspects of the build system so I'll take a look.

**Pull request merged**
