### PR TITLE
Added raylib-APL to BINDINGS.md

### PR DESCRIPTION
**Pull request by Brian-ED**

### CODE REVIEW

**Comment by Brian-ED** [comment]
Oh i accidentally removed a newline! give me a minute or two

**Comment by Brian-ED** [comment]
done, now ready for merge

**Comment by Brian-ED** [comment]
I realized raylib-apl isn't *auto*, it's raylib 5.0. will edit that too

**Comment by Brian-ED** [comment]
Fixed, now ready for merge again.

**Comment by raysan5** [comment]
@Brian-ED thanks for the addition!

**Pull request merged**
