### PR TITLE
Augment raymath.h with useful functions

### PR DESCRIPTION
**Pull request by saccharineboi**
I use these functions heavily during gamedev so I thought they could be useful for others too:

- FloatEquals:  Check whether two given floats are almost equal
- Vector{n}Invert: Invert the given vector
- Vector{n}Clamp: Clamp the components of the vector between min and max values specified by the given vectors
- Vector{n}ClampMagnitude: Clamp the magnitude of the vector between two given min and max values
- Vector{n}Equals:  Check whether two given vectors are almost equal

Additionally Vector3{Up,Down,Left,Right,Forward,Backward} are added for convenience.

Vector3Refract refracts a vector given a normal and a refractive index.

QuaternionEquals checks whether two given quaternions are almost equal.

Furthermore, a macro named "EPSILON" with a value 1e-6 is added (used in floating-point comparison functions), and stdbool.h is included for functions that return boolean values.

### CODE REVIEW

**Comment by CrezyDud** [comment]
rename Vector2ClampMagnitude and Vector3ClampMagnitude to Vector2ClampValue and Vector3ClampValue
for consistency

**Comment by raysan5** [comment]
@saccharineboi I think some of those functions are unneded and just add a level of undirection not required. i.e users cand define required Vector3 up/down/back...  directly, no need to provide functions for everything.

**Comment by raysan5** [comment]
@saccharineboi thanks for the review.

**Comment by planetis-m** [comment]
I don't know if it's intentional or an oversight but missing from this PR is MatrixEquals.

**Comment by raysan5** [comment]
@planetis-m Could you list a use case for that function?

**Comment by saccharineboi** [comment]
> I don't know if it's intentional or an oversight but missing from this PR is MatrixEquals.


Intentional. In contrast to Vector{n}Equals which is useful for checking degenerate vectors, MatrixEquals is almost never used. Though it could be added for completeness' sake.


@raysan5 what do you mean it broke raylib? Was it because of stdbool.h? Instead of removing those functions, you could change return types to int

**Comment by raysan5** [comment]
@saccharineboi I already change return types to int.

**Pull request merged**
