### PR TITLE
[build] [web] Use `mingw32-make` for `PLATFORM_WEB` examples `Makefile` on Windows

### PR DESCRIPTION
**Pull request by asdqwe**
Ref: https://github.com/raysan5/raylib/pull/4434#issuecomment-2438953574, https://github.com/raysan5/raylib/pull/4434#issuecomment-2439001173.

Note: I don't have Windows here, so please double check/test this PR.

### CODE REVIEW

**Comment by raysan5** [comment]
@asdqwe thanks for the review, looks good

**Comment by Peter0x44** [comment]
@asdqwe what toolchain distribution did you find that has mingw32-make but no normal make?

**Comment by asdqwe** [comment]
@Peter0x44 Not sure how that relates to this PR.

Since ea325c54e89743432eef7b22e724515b53501767 (which was one year ago) `emmake` was being used. 

eb04154c98616f0355b0035945a58fa7b56d59e2 (3 days ago) changed it to `mingw32-make`, which may not be present (e.g.: Linux host, not cross-compiling for Windows) and broke compiling the examples on those cases.

So #4434 (yesterday) was submitted to fix that by checking if `emmake` was present. If it was, use it as it used to. If it wasn't, then falling back to `mingw32-make` to comply with eb04154c98616f0355b0035945a58fa7b56d59e2.

Then @raysan5 pointed this known issue: https://github.com/emscripten-core/emscripten/blob/main/emmake.bat#L42. So this #4436 was made prefer `mingw32-make` on Windows, where, on the context of compiling raylib, it's likely to be present.

**Comment by Peter0x44** [comment]
Wouldn't it be better to just use make everywhere?

**Comment by asdqwe** [comment]
In my opinion, despite a common sight (and quite standard) on Linux, I don't think regular `make` (or a symlink to it) is readily available on every other platform (specially on Windows, although WSL has it now). Specifically for building `PLATFORM_WEB`, raylib requires `emcc`, and `emcc` is provided by the `emsdk` which also ships `emmake`:
```
~/emsdk/upstream/emscripten$ ls em*
em++           embuilder.py     emdump.bat     emranlib.bat             emsize.bat
em++.bat       emcc             emdwp          emranlib.py              emsize.py
em++.py        emcc.bat         emdwp.bat      emrun                    emstrip
em-config      emcc.py          emmake         emrun.bat                emstrip.bat
em-config.bat  emcmake          emmake.bat     emrun.py                 emstrip.py
em-config.py   emcmake.bat      emmake.py      emscons                  emsymbolizer
emar           emcmake.py       emnm           emscons.bat              emsymbolizer.bat
emar.bat       emconfigure      emnm.bat       emscons.py               emsymbolizer.py
emar.py        emconfigure.bat  emprofile      emscripten-revision.txt
embuilder      emconfigure.py   emprofile.bat  emscripten-version.txt
embuilder.bat  emdump           emranlib       emsize
```

So I'd say it's safe to assume that if `emcc` is present (as required), `emmake` probably would be present too. Besides, `emmake` has been in use for a year now, so it looks stable enough.

**Pull request merged**
