### PR TITLE
[CORE] Allow for setting a array of icons instead of only one

### PR DESCRIPTION
**Pull request by SplatTab**
Allow for setting a array of icons (most likely different resolutions) instead of just one icon

### CODE REVIEW

**Comment by raysan5** [comment]
@SplatTab Sorry, I'm not changing that function, others users could be using it and probably most users don't need to set more than one icon. If you need that advance functionality I recommend calling GLFW directly.

**Comment by SplatTab** [comment]
Yea but you could still set only one icon and it would be annoying to have to add GLFW for others

**Comment by SplatTab** [comment]
I guess that's fair I'll just patch it so that I can set my second icon

**Comment by raysan5** [comment]
@SplatTab Why do you need to set your icons in runtime? If they are static they are usually set as an icon resource at compilation time.

**Pull request closed without merging**
