### PR TITLE
Fix issue #3665

### PR DESCRIPTION
**Pull request by CMDisme**
Set cubemap format in LoadTextureCubemap

### CODE REVIEW

**Comment by CMDisme** [comment]
Fixes #3665

**Comment by raysan5** [comment]
@CMDisme how did you test this change if there is no code example to test it?

**Comment by CMDisme** [comment]
I copied the code from the issue

**Comment by raysan5** [comment]
@CMDisme Ok, I see, but I'm afraid that code does not verify if the loaded cubemap is actually valid. And example would be required to review it.

**Pull request closed without merging**
