### PR TITLE
[rtext] Fix default font alpha on Big Endian systems

### PR DESCRIPTION
**Pull request by Fancy2209**
Alpha was broken for rtext's default font on Big Endian
Before
imagem
After
imagem

### CODE REVIEW

**Comment by raysan5** [comment]
@Fancy2209 It seems this patch addresses a specific use case for a specific hardware arquitecture... won't endianness affect other parts of raylib library? 🤔

**Comment by Fancy2209** [comment]
I tested some examples and they work, but I still have to test loading assets

Also it isn't just PowerPC/PowerPC64  




I'll search for further issues with Big Endian
By the way, it isn't just PowerPC that's big endian, it's just the more common one

**Comment by Peter0x44** [comment]
Big endian is uncommon, but worth supporting. This will break all big endian systems, like powerpc linux, and sparc linux. Not that they are common, but it still matters to some users.

**Comment by Fancy2209** [comment]
> Big endian is uncommon, but worth supporting. This will break all big endian systems, like powerpc linux, and sparc linux. Not that they are common, but it still matters to some users.

You mean this issue affects them too or that this PR breaks them?

**Comment by Peter0x44** [comment]
I mean the issue affects them. I think sparc and powerpc are the most relevant BE systems

**Comment by raysan5** [comment]
@Fancy2209 @Peter0x44 what is the cost of supporting big endian in raylib? It can require many changes and additional code complexity for a very specific set of platforms... if it implies only a couple of checks, it can be considered...

**Comment by Fancy2209** [comment]
I have to test all examples and find issues so it might take a bit
According to an article Peter0x44 code should always be endian independent anyways so it shouldn't be too hard to patch
I'll do a torough testing spree of all tests in a bit, fix the missing tests and report back

**Comment by raysan5** [comment]
@Fancy2209 ok, nice! 👍😄

**Comment by orcmid** [comment]
@raysan5 keep in mind that endian-ness only crops up when one presumes which end bits are in for numerical types with size larger than one byte.  The peculiar case, the one addressed here, is when an int is intended to pack two single-byte values: forming a mini-struct.   I trust that is a very unusual case in raylib and libraries it depends upon.

**Comment by Peter0x44** [comment]
It implies no extra complexity, just a few minor edge cases need some extra care and attention
This case can actually be rewritten not to need the ifdef by writing both bytes of the short separately
Something like:

```c
((unsigned char *)imFont.data)[(i + j)*sizeof(short)] = 0x00;
((unsigned char *)imFont.data)[(i + j)*sizeof(short) + 1] = 0xFF;
```

**Comment by Fancy2209** [comment]
> It implies no extra complexity, just a few minor edge cases need some extra care and attention This case can actually be rewritten not to need the ifdef by writing both bytes of the short separately Something like:
> 
> ```c
> ((unsigned char *)imFont.data)[(i + j)*sizeof(short)] = 0xFF
> ((unsigned char *)imFont.data)[(i + j)*sizeof(short) + 1] = 0x00;
> ```

Done, I still have to test loading Data though

**Comment by raysan5** [comment]
@Fancy2209 please, let me know when ready! did you test some examples to see other possible related point to review?

**Comment by Peter0x44** [comment]
This change only applies to loading the default font and is fine on its own.
There might be other issues with endianness to review but there is no reason not to merge this one.

**Pull request merged**
